### ISSUE TITLE
WebHelper

### ISSUE THREAD

**Issue by loushou** [Baseflow/flutter_cache_manager#101]
Can you expose the `WebHelper` class publicly in the package?

It would be useful, because currently, you allow us to write our own extensions of the `BaseCacheManager`; however, if we want to improve the `webHelper` to handle more status codes (for instance), then we have to overwrite every function that uses the `webHelper` object if we want to customize it. If we had access to the `WebHelper` class, we could not only write a custom `CacheManager`, but also a custom `WebHelper` that contains our own business logic.

Alternatively, there may be a shorter way to customize this that I am missing, and I am willing to admit that. If there is, could you point us to the methodology for doing this, that does not require a complete rewrite of every function in my custom `CacheManager`?

Thanks

**Comment by loushou** [comment]
Also I guess in order to expose this, you will also need to expose CacheObject and CacheStore.

**Comment by loushou** [comment]
Yeah as it stands right now, we actually cannot effectively write our own `CacheManager` unless it is super simple, and does not require use of the `CacheObject`/`CacheStore` classes. I basically will have two rewrite the whole implementation so I can use my own equivalent classes if I want to make my own CacheManager...

that is all of course, unless I am missing something...

P.S. - i can get around this by importing your 'implementation' files, but according to flutter/dart best practices, we should not do that because the file names could change in future releases.

**Comment by C2N14** [comment]
I know it's been a while, but I would love to see if this has been taken into consideration :)

**Comment by martijn00** [comment]
https://github.com/Baseflow/flutter_cache_manager/pull/371
https://github.com/Baseflow/flutter_cache_manager/pull/378
