### ISSUE TITLE
How to control network timeout duration?

### ISSUE THREAD

**Issue by zubairehman** [Baseflow/flutter_cache_manager#102]
Hi,

Thanks for such a great plugin.
How can i control network timeout duration? Right now the error widget gets called after 3-5 mins when there is no connection. I want it get called right after it failed to fetch image or may be after 5 seconds. Help will be appreciated :)

**Comment by yrom** [comment]
You can try [HttpOverrides](https://api.flutter.dev/flutter/dart-io/HttpOverrides-class.html) to override the httpclient
