### ISSUE TITLE
Changing the cache duration (maxAgeCacheObject of the CacheManager) is not working

### ISSUE THREAD

**Issue by olafurorng** [Baseflow/flutter_cache_manager#106]
Images which are being cached, by using the `flutter_cached_network_image` package, are being cached for longer time than I specify.

I see that `BaseCacheManager` has default cache duration as 30 days (`Duration maxAgeCacheObject = const Duration(days: 30)`), but I would like to have the cache duration as 2 minutes.

I tried to create a new cache manager, which extends `BaseCacheManager` and overwrites the `maxAgeCacheObject`

```
class ImageCacheManager extends BaseCacheManager {
  static const key = "libCachedImageData";

  static ImageCacheManager _instance;

  factory ImageCacheManager() {
    if (_instance == null) {
      _instance = new ImageCacheManager._();
    }
    return _instance;
  }

  ImageCacheManager._() : super(key, maxAgeCacheObject: Duration(minutes: 2));

  Future<String> getFilePath() async {
    var directory = await getTemporaryDirectory();
    return p.join(directory.path, key);
  }
}
```

But still, the images are being cached for more than 2 minutes.

**Comment by tim-fdc** [comment]
Hi,
 In my case the reason is the `WebHelper`, which sets the default time to 7 days if the `cache-control` header has `max-age=0` (if set at all). See `WebHelper` lines 109 ff. The `maxAgeCacheObject` of the `BaseCacheManager` is a max age regardless of the setting of an individual `CacheObject` (as far as I read the code).

Would be great to get more client side control about the max caching time.

Happy hakking!

**Comment by tihomir-stefanov** [comment]
What you could do is when you create your own CacheManager, you could have a custom **fileFetcher** and inside you could set max-age=120 (seconds).

` ImageCacheManager._()
      : super(
          key,
          maxAgeCacheObject: Duration(minutes: 2),
          fileFetcher: _customHttpGetter,
        );

  static Future<FileFetcherResponse> _customHttpGetter(String url, {Map<String, String> headers}) async {
    // Do things with headers, the url or whatever.
    Response httpResponse = await http.get(url, headers: headers);
    httpResponse.headers.addAll({'cache-control': 'max-age=120'});
    return new HttpFileFetcherResponse(httpResponse);
  }`

**Comment by patniemeyer** [comment]
I was also confused when I set the cache max age and it had no effect.  It appears that the cache is only respecting the HTTP `cache-control` header for items downloaded over web and ignoring the cache max age itself.

**Comment by renefloor** [comment]
@patniemeyer the max age of the cachemanager is used, but perhaps differently than you expect. I'll clarify the docs (or even change the variable name). When you set the max age to, for example, a week, the cached file will be removed when it is not used for a week. When you use it, but it is still valid according to the cache-control header the file is kept in the cache for another week.

**Comment by Xgamefactory** [comment]
> fileFetcher

Filefetcher is now deprecated (Use FileService instead)
