### ISSUE TITLE
getFileFromCache and getSingleFile documentation

### ISSUE THREAD

**Issue by EricPreventa** [Baseflow/flutter_cache_manager#124]
What I'm trying to do is cache the file, display it. Then in a later step, get access to that cached file and upload it. When I've previously used getSingleFile, it worked, but in the later step when I used getFileFromCache, it was not there. 

I used getSingleFile and it works fine, but not sure where it falls into these options. What do I need to do to accurately use getFileFromCache? I'm still not following what the differences or when to use the following. 

getFile(url) returns a stream with the first result being the cached file and later optionally the downloaded file.

downloadFile(url) directly downloads from the web.

getFileFromCache only retrieves from cache and returns no file when the file is not in the cache.

**Comment by renefloor** [comment]
You are completely right about them all. getSingleFile is mostly like getFile.

An ImageProvider can't show 2 images after each other, so I couldn't use getFile for that. getSingleFile tries to get the file from the cache, if it has one it returns the cache. If the cache is outdated it updates it in the background after returning the file. When it has no cache it downloads the file and returns the download while saving it in the cache.

I'll improve the docs

**Comment by EricPreventa** [comment]
I appreciate the help, and can't thank you enough for this wonderful cache manager. 

What would you suggest is the best thing to use to get a file from url, then at a later step get that file from cache?

I tried using getSingleFile (that worked great in getting the file), but then getFileFromCache at a later step did not seem to get the cached file from getSingleFile. 

Am I using those steps correctly?

**Comment by renefloor** [comment]
getFileFromCache should work in that case, thus this sounds like a bug. Maybe something goes wrong with the caching of a specific file. Could you give me a minimal example in which you reproduce this issue (including the affected url)? 

Does it work for any url you tried? At this moment I cannot try to reproduce it.

**Comment by EricPreventa** [comment]
I'm trying to access an http on a local server. So my example may not work for other URLs. However I'll try it again though and see if I have any luck. 

Is getSingleFile best to use for the getFileFromCache? Or would another getFile work better?

**Comment by renefloor** [comment]
If you'd like to work with a stream I really recommend to use getFile. If you prefer a Future with only 1 result you can always use getSingleFile. This should not do an api call everytime and just return the file from cache if it is available. I say should as getFileFromCache also should return the file. 

getFileFromCache only makes sense when you really don't want the library to update the file. For example when you work with large files I can imagine you call getSingleFile or getFile when you are on wifi and getFileFromCache when you are using a mobile connection.

**Comment by EricPreventa** [comment]
Thanks @renefloor for your help.

Lastly, downloadFile(url) can you explain the usage of this? Does this physically download it (to what path if so?) and is it no longer considered being "cached"? If downloaded, do you decide where it goes, and if you were to use removeFile(url) does that still remove (delete) it to wherever it was downloaded to?

**Comment by renefloor** [comment]
You always have to download the file to cache it, this method also caches the file like the other methods.
It is in some way similar to getFileFromCache. getFileFromCache forces the lib to only use the cache, although the file is outdated or doesn't exist. downloadFile forces the lib to download the file, although it might already have the file in cache.

Some APIs don't use cache headers correctly and than the online file might already have changed while the cache is still valid. If you know that is the case you could use this method to bypass the cache.
