### ISSUE TITLE
缓存的音频文件为何播放时其他缓存的图片要闪烁

### ISSUE THREAD

**Issue by mengsiyitiaojie** [Baseflow/flutter_cache_manager#126]
怎么解决这个问题啊

**Comment by petermichaux** [comment]
Google Translate says

"Why do other cached pictures flash when the cached audio file is playing?"

"How to solve this problem"

**Comment by jlcool** [comment]
图片闪烁可能是图片太大了，压缩显示吧

**Comment by renefloor** [comment]
If there is still an issue please make a new one in English. I can only support English and working through Google Translate is not really working.
