### ISSUE TITLE
package problem because of getApplicationDocumentsDirectory() 

### ISSUE THREAD

**Issue by RafaelR7** [Baseflow/flutter_cache_manager#134]
Hi, I'm having an issue with the packages because it uses the `path_provider` function `getApplicationDocumentsDirectory()`, in my app I need to be able to download a pdf file and save it, on IOS to save to `Files`, I also using the `getApplicationDocumentsDirectory()` and I had to edit the `info.plist` and add this lines, so the folder is visible to the user:
`<key>LSSupportsOpeningDocumentsInPlace</key>
<true/>
<key>UIFileSharingEnabled</key>
<true/>`

The problem is, since the package is also using getApplicationDocumentsDirectory,  the folder has some files that the user shouldn't be seeing. 
Looking into the `path_provider` package it says to use `getApplicationSupportDirectory()` for files that shouldn´t be visible to the user [,](https://github.com/flutter/plugins/blob/master/packages/path_provider/lib/path_provider.dart) I think this package should be using  `getApplicationSupportDirectory()`  instead of  `getApplicationDocumentsDirectory()`.

**Comment by renefloor** [comment]
Sorry for my late response, but this package doesn't use getApplicationDocumentsDirectory by default, but getTemporaryDirectory and as far as I know it always did.

**Comment by josh-burton** [comment]
I'm running into this issue as well. It's strange because the default cache manager uses the correct path (/Library/Caches) but the db file is still visible in the Files application.
