### ISSUE TITLE
FileSystemException: Cannot open file, path = '***.jpg' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by pxc0215** [Baseflow/flutter_cache_manager#135]
My online app get lots of exception as follows：

FileSystemException: Cannot open file, path = '/data/user/0/com.example.flutter/cache/libCachedImageData/a3a66950-2dc9-11ea-f2a6-3f3671df8934.jpg' (OS Error: No such file or directory, errno = 2)

How can I resovle? Very thanks!

**Comment by pxc0215** [comment]
The detail log stacktrace as:

`stacktrace:  #0 _File.open.<anonymous closure> (dart:io/file_impl.dart:364)#1 _rootRunUnary (dart:async/zone.dart:1132)#2 _CustomZone.runUnary (dart:async/zone.dart:1029)#3 _FutureListener.handleValue (dart:async/future_impl.dart:137)#4 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)#5 Future._propagateToListeners (dart:async/future_impl.dart:707)#6 Future._completeWithValue (dart:async/future_impl.dart:522)#7 Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)#8 _rootRun (dart:async/zone.dart:1124)#9 _CustomZone.run (dart:async/zone.dart:1021)#10 _CustomZone.runGuarded (dart:async/zone.dart:923)#11 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)#12 _microtaskLoop (dart:async/schedule_microtask.dart:41)#13 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)`

**Comment by Unicellular-SU** [comment]
I am having exact same issue

**Comment by lenva** [comment]
I found a way to reproduce:
1. Open the Flutter app and load some pictures
2. Go to the Application Settings of Android system to clear the application cache. Do not clear all data
3. At this point, go back to your Flutter app and look at the image loaded. The image cannot be displayed and the log will be printed
4. The key point is that clearing the app cache will not kill the APP process, and restarting the app will restore normal

**Comment by Soon96** [comment]
hi, having error :  Another exception was thrown: FileSystemException: Cannot open file, path = '/data/user/0/.../' (OS Error: No such file or directory, errno = 2). now even you do not clear cache will have this problem too,  any work around or solution for now?

**Comment by nugatritter** [comment]
Same problem with FileSystemException here. Is there any workarround?

**Comment by Soon96** [comment]
hi any update on this issue ?

**Comment by wochen85** [comment]
I have the exactly same problem, is any update?
@pxc0215 ，have you fix that? can you tell me what is your solution 😊？

**Comment by talhakosen** [comment]
Below is my work around solution

```
class CustomCachedImage extends StatefulWidget {
  final String imageUrl;
  final double radius = 20.0;

  CustomCachedImage({
    @required this.imageUrl,
  });

  @override
  _State createState() => _State();
}

class _State extends State<CustomCachedImage> {
  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(
      imageUrl: widget.imageUrl,
      imageBuilder: (context, imageProvider) {
        return Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.all(Radius.circular(widget.radius)),
            image: DecorationImage(
              image: imageProvider,
              alignment: Alignment.topCenter,
              fit: BoxFit.cover,
              scale: 1,
            ),
          ),
        );
      },
      placeholder: (BuildContext context, String url) => Container(),
      // If error happens load image by using NetworkImage 
      errorWidget: (context, url, error) {
        return Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.all(Radius.circular(widget.radius)),
            image: DecorationImage(
              image: NetworkImage(widget.imageUrl),
              alignment: Alignment.center,
              fit: BoxFit.cover,
              scale: 1,
            ),
          ),
        );
      },
    );
  }
}
```
