### ISSUE TITLE
Control over extension

### ISSUE THREAD

**Issue by chris-rutkowski** [Baseflow/flutter_cache_manager#136]
Hello,
the Audio Player on iOS is very sensitive about file extension, otherwise, it fails to play the file.

When I do the following operation:

```
final url = 'http://audio.oxforddictionaries.com/en/mp3/escort_gb_1.mp3';
final file = await DefaultCacheManager().getSingleFile(url);
print(file.path)
```

The output in the console is **4d175ef0-2f5e-11ea-b93f-5b47edede79b.octet-stream**.

As you see the default extension is lost, the file ends with octet-stream. There could be many other reasons why the extension should be preserved.

I'm using most recent stable Flutter and Flutter cache manager.

**Comment by renefloor** [comment]
Yes it needs a better way to convert MIME types to file extensions.
I guess this PR would be perfect for that: https://github.com/dart-lang/mime/pull/15

**Comment by renefloor** [comment]
@chris-rutkowski Do you have access to the server? The file you like has a content_type of binary/octet-stream, which even with a better mime interpreter it would not result in a .mp3 file. Do you have a way to set the content_type header to audio/mpeg?

**Comment by chris-rutkowski** [comment]
No, I don't have access to the server, it's public API

**Comment by renefloor** [comment]
I'm thinking how I can add some control nicely without making the api confusing

**Comment by renefloor** [comment]
You can now make a custom FileService if you really want to do this.

**Comment by jiangyh1024** [comment]
@chris-rutkowski how to solve this problem ? I'm encountering this problem too

**Comment by chris-rutkowski** [comment]
@jiangyh1024 I created my own solution. You just need the path provider package to write to correct purpose directories (cache/documents/tmp), and built-in file operations with dart are very easy. https://api.dart.dev/stable/2.8.2/dart-io/File-class.html

**Comment by jiangyh1024** [comment]
@chris-rutkowski  you mean get the file path first for example as you state (4d175ef0-2f5e-11ea-b93f-5b47edede79b.octet-stream.) and write it to another file  for example  xxx.mp3 ?

**Comment by chris-rutkowski** [comment]
@jiangyh1024 nah, I abandoned this package (flutter_cache_manager). You can download the file using any http client, and save it yourself having full control on directory and file name (for big files it should be streamed directly to file).

**Comment by jiangyh1024** [comment]
ok thank you

**Comment by shubhamsinghmutualmobile** [comment]
> Issue: Incorrect File Extension When Downloading with flutter_cache_manager
> 
> Hi!
> 
> I encountered a similar issue where an `.mp3` file was being downloaded as a `.bin` file using `flutter_cache_manager` (version ^3.3.1 on MacOS).
> 
> #### Workaround:
> To resolve this, I used `flutter_cache_manager` to download the file initially with the temporary extension `.bin`. After downloading, I re-saved the file using `putFileStream()` with the correct `.mp3` extension, then deleted the temporary file. Here's how I implemented it:
> 
> ```dart
>     final tmpTrackFile = await _cacheManager.getSingleFile(trackUrl, key: '${trackKey}_tmp');
>         trackFile = await _cacheManager.putFileStream(
>           trackUrl,
>           tmpTrackFile.openRead(),
>           fileExtension: 'mp3',
>           key: trackKey,
>         );
>         await _cacheManager.removeFile('${trackKey}_tmp');
> ```

This worked for me! Thanks a bunch 🎉
