### ISSUE TITLE
Downloaded mp3 file was converted to mpeg file

### ISSUE THREAD

**Issue by somaria** [Baseflow/flutter_cache_manager#140]
Hi,

I have used Flutter Cache Manager to download some mp3 files but the files were converted to mpeg.

It seems that in iOS, you can't play an mpeg file.  

Anyone has any suggestion on what I can do?  Any suggestions would be greatly appreciated.

**Comment by suragch** [comment]
Do you have access to the backend? I think I was getting this problem but then solved it by changing the content type of the response to `audio/mp3` instead of `audio/mpeg`. If you don't have access to the backend then I would try just renaming the file to have an extension of `.mp3`.

**Comment by Skuallpa** [comment]
I'm also facing the same issue. I'm trying to cache some mp3 files but they get renamed with .mpeg extension.

Is it possible to rename the files in the cache ?

**Comment by renefloor** [comment]
This PR fixes this, but I don't know when I'll make a new release yet: https://github.com/Baseflow/flutter_cache_manager/pull/150/files#diff-905135c7c1aed5fab30a695cfc2aaf38
