### ISSUE TITLE
Don't swallow exceptions

### ISSUE THREAD

**Issue by osoftware** [Baseflow/flutter_cache_manager#142]
## 🏗 Enhancement Proposal

There are places in code that catch all exceptions and just return null. This is generally a bad practice and it costed me yesterday a rejected iOS app deployment and several hours of blindly searching for the root of problem. The exception should be passed through (easy) or wrapped with a custom one (elegant).

### Pitch

It would save me several hours it I got the actual exception that was thrown by the fileFetcher rather than vague null ref exception several app layers away.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
@osoftware I guess this commit would fix it right? I'll merge it soon, I'm not sure when I'll release a new version though. You could use that branch directly for now if you want to.

**Comment by renefloor** [comment]
Sorry, I meant this commit: https://github.com/Baseflow/flutter_cache_manager/commit/d3f8729041bdee694d539a199017e88ef001c7fd

**Comment by osoftware** [comment]
Yep, that's ok.
