### ISSUE TITLE
Add support for macOS

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Baseflow/flutter_cache_manager#149]
### Describe the feature
Currently using CachedNetworkImage fails for 2 reasons, I believe:

1. the version of the path_provider dependency doesn't support mac. (v1.6.5 does)
2. the version of  sqflite used doesn't support mac yet. (v1.3.0 does)

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [X] macOS

**Comment by ThinkDigitalSoftware** [comment]
After overriding the dependencies in the pubspec of my project, images load fine

**Comment by AndroidNils** [comment]
+1

**Comment by renefloor** [comment]
Running packages upgrade should already fix the dependencies, it gets the newest version with the same major version. I'll update the dependencies for the next release, but that shouldn't be a problem for now.
