### ISSUE TITLE
Future doesn't return the new data after max age

### ISSUE THREAD

**Issue by jfrcom** [Baseflow/flutter_cache_manager#156]
### Expected behavior

I'm not really sure if it is a bug or if there's something wrong with my code.
I've made a `CustomCacheManager` that makes files in cache invalid after 20 minutes. However when I open my app for example after several hours it still loads the old data from cache (I think it then saves the new data to the cache though). When I then change screen and go back to the same screen it loads the new data from cache.

### Reproduction steps

I'm using a `FutureBuilder` but my `Future` does not return the new data after 20 minutes. Only after changing screens. 

My `CustomCacheManager` looks like this:

```dart
class CacheManager extends BaseCacheManager {
  static const key = "customCache";

  static CacheManager _instance;

  factory CacheManager() {
    if (_instance == null) {
      _instance = new CacheManager._();
    }
    return _instance;
  }

  CacheManager._()
      : super(key,
            maxAgeCacheObject: Duration(minutes: 20),
            maxNrOfCacheObjects: 20,
            fileFetcher: _myHttpGetter);

  @override
  Future<String> getFilePath() async {
    var directory = await getTemporaryDirectory();
    return path.join(directory.path, key);
  }

  static Future<FileFetcherResponse> _myHttpGetter(String url,
      {Map<String, String> headers}) async {
    HttpFileFetcherResponse response;
    try {
      var res = await http.get(url, headers: headers);
      res.headers.addAll({'cache-control': 'private, max-age=1200'});
      response = HttpFileFetcherResponse(res);
    } on SocketException {
      print('No internet connection');
    }
    return response;
  }
}
```

and my `Future` like this: 

```dart
Future<List> getStats() async {
    final url =
        'someURL';

    final response = await CacheManager().getSingleFile(url);

    if (response != null && await response.exists()) {
      final res = await response.readAsString();
      final finalList = MyData.fromJson(json.decode(res));
      return finalList;
    }
    throw Exception();
  }
```

Please let me know if this behavior is as expected or if it is a bug.

### Configuration

**Version:** 1.1.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
I'm not sure if I understand you correctly, but if I do that is intended behaviour. 

See [the docs](https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/BaseCacheManager-class.html): 
> getSingleFile(String url, {Map<String, String> headers}) → Future<File>
> Get the file from the cache and/or online, depending on availability and age. (...) When a file is cached it is return directly, when it is too old the file is downloaded in the background. When a cached file is not available the newly downloaded file is returned. 

When max-age is reached it is not known whether the file is valid or not, but it doesn't necessarily means it is invalid. Especially for images it is often more important to serve the file as quick as possible than making completely sure it is up to date. 

The other function `getFile` also returns the cached file directly, but after updating online it also returns the new file, hence the stream. I don't know your usecase, but that could be a better function for you.
