### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The getter 'inMicroseconds' was called on null

### ISSUE THREAD

**Issue by dao-wkm** [Baseflow/flutter_cache_manager#157]
Thanks for reading

## 🐛 Bug Report
E/flutter ( 4036): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'inMicroseconds' was called on null.
E/flutter ( 4036): Receiver: null
E/flutter ( 4036): Tried calling: inMicroseconds
E/flutter ( 4036): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 4036): #1      DateTime.subtract  (dart:core-patch/date_patch.dart:197:54)
E/flutter ( 4036): #2      CacheObjectProvider.getOldObjects 
package:flutter_cache_manager/src/cache_object.dart:151
E/flutter ( 4036): #3      CacheStore._cleanupCache 
package:flutter_cache_manager/src/cache_store.dart:136
E/flutter ( 4036): <asynchronous suspension>
E/flutter ( 4036): #4      CacheStore._scheduleCleanup.<anonymous closure> 
package:flutter_cache_manager/src/cache_store.dart:123
E/flutter ( 4036): #5      _rootRun  (dart:async/zone.dart:1122:38)
E/flutter ( 4036): #6      _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter ( 4036): #7      _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter ( 4036): #8      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter ( 4036): #9      _rootRun  (dart:async/zone.dart:1126:13)
E/flutter ( 4036): #10     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter ( 4036): #11     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:949:23)
E/flutter ( 4036): #12     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 4036): #13     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter ( 4036): #14     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter ( 4036): #15     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)

**Version:** 1.1.3

**Platform:** 
- [X] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
Do you have any idea when or why this happens?

**Comment by dao-wkm** [comment]
> Do you have any idea when or why this happens?

This error is thrown many times while running the app

**Comment by dao-wkm** [comment]
> Do you have any idea when or why this happens?

I dont know why but this error is thrown many times while running the app

**Comment by dao-wkm** [comment]
I don't see any errors in this case anymore after upgrade flutter to master v1.20.0-7.0.pre, cached_network_image: 2.2.0+1
