### ISSUE TITLE
When 2.0 release? I really need 2.0 to cache pdf file

### ISSUE THREAD

**Issue by xilibro** [Baseflow/flutter_cache_manager#159]
When 2.0 release? I really need 2.0 to cache pdf file
1.1.3 downloaded pdf file's extension is 

1d039440-74c3-11ea-b046-377c3234c477.json;charset=UTF-8

**Comment by renefloor** [comment]
No ETA, but if 1.1.3 converts to type .json version 2.0 will do as well. Only content-type 'application/pdf' will turn to pdf and that doesn't change.

**Comment by xilibro** [comment]
Thanks for response.

**Comment by renefloor** [comment]
It's not about the headers you send, but about the response from the server. If the server says it is a json file it is saved as a json. If you give me the pdfUrl I can show you the headers you receive. (If it is public)

**Comment by xilibro** [comment]
OK，many thanks, i will fix it with my colleague(server side)
