### ISSUE TITLE
Avoid memory cache, support file only

### ISSUE THREAD

**Issue by sowens-csd** [Baseflow/flutter_cache_manager#163]
## 🚀 Feature Requests

Configure the cache to never store cached items in memory. 

Support the ability to configure the cache to not put cached items into an in memory cache. Always retrieve from file every time to avoid the memory use. 

### Contextualize the feature

Possibly allow a simple override of the CacheStore to support this? You could do that by having a single method like putFileInMemory that could be overridden as a no-op. Either that or a constructor flag or other mechanism to configure the behaviour. 

### Describe the feature

I'd like to lower the memory footprint of my application as much as possible. I'm storing some reasonably large files in the cache so I don't have to go back to the network to retrieve them but loading them from disk every time would give fine performance.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by sowens-csd** [comment]
Looks like I should have looked more closely at the implementation before asking. I think only the meta information is cached in memory, if so, there's no need for this feature.

**Comment by renefloor** [comment]
Yes, I should have to make some tests, but as far as I know the memory usages is quite small.
