### ISSUE TITLE
Is it possible to handle file extension with content-type that has defined charset

### ISSUE THREAD

**Issue by xilibro** [Baseflow/flutter_cache_manager#164]
## 🚀 Feature Requests
My file server return file with content-type as flowing:
content-type: application/pdf;chartset=UTF-8

Can you consider this case when handle file extension?

**Comment by renefloor** [comment]
Yes of course, I thought it already did. Will fix it quickly

**Comment by renefloor** [comment]
@xilibro fixed in 1.2.1
