### ISSUE TITLE
Duration is always "about" 7 days.....

### ISSUE THREAD

**Issue by lgLindstrom** [Baseflow/flutter_cache_manager#170]
Hi

I am working on a Weather app and planned to use OpenWeatherMap as weather provider of weather data,

For this I also want to use flutter_cache_manager to avoid not necessary calls to OpenWeatherMap.

I have followed your example to create a cache manager only for fetching weather data. 

`
```
  class WeatherCacheManager extends BaseCacheManager {
  static const key = "weatherCache";
  static WeatherCacheManager _instance;
  factory WeatherCacheManager() {
    if (_instance == null) {
      _instance = new WeatherCacheManager._();
    }
    return _instance;
    }
    WeatherCacheManager._() : super(key,
       maxAgeCacheObject: Duration(seconds: 120),
    );
    Future<String> getFilePath() async {
    var directory = await getTemporaryDirectory();
    return path.join(directory.path, key);
    }
   }
```
`

I am using it like this
```
`...
response = await WeatherCacheManager().getSingleFile(currentWeather);
...
`
```

Please notice that the duration of 120 s is only for testing.

I quickly noticed that data from OpenWeatherMap never was updated. Digging into this showed me that despite from start when cache was empty, I never got any updates from the website. Data was always fetched from storage.

Looking even futher into this I also noticed that "cacheFile.validTill"  always was set to about 7 days in the future. ( I traced in getSingleFile function).

So, this is kind of basic function for a cache manager so I assume that I am doing something wrong.
But what????
Can I have som help please?

**Comment by renefloor** [comment]
I guess this is the same issue as #106, the documentation is not clear about it.

The maxAgeCacheObject is not about the maximum age of each item in the cache, that is always determined by the cache headers (if possible). The maxAgeCacheObject determines whether I file should be removed based on the last time the file is used. 

If you load multiple items, restart the app and load other items, the cache cleaning will start. If the items haven't been used for 120 seconds they will be removed from the cache. If you use the same items every time you open the app the cache items will never be old in the sense of unused, so they are not removed.

**Comment by lgLindstrom** [comment]
I understand. So I can't use this package the way I intendent, avoid to many accesses to the web service. I have no control over the way users are starting and stopping the application.

**Comment by renefloor** [comment]
@lgLindstrom You can create a custom [FileService](https://github.com/Baseflow/flutter_cache_manager/blob/develop/lib/src/web/file_service.dart) and set the validTill value to anything you want.
