### ISSUE TITLE
Full custom path

### ISSUE THREAD

**Issue by spiderion** [Baseflow/flutter_cache_manager#173]
## 🚀 Feature Requests

My custom cache manager should allow me to create a fully customizable directory path.

### Contextualize the feature
Currently, I need to download some video files on the local storage and for some reasons the device only accepts paths that end with .mp4
if the path doesn't end with .mp4 format the video is not played.

### Describe the feature
When we create the custom cache manager the path that we need to provide the customCacheManager is only partially customizable and doesn't allow me to set the file format.
For this reason, some video than doesn't end with the format .mp4 are not working correctly.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
@spiderion the path is just where the file is located. You can also supply a custom FileService, that is where the extension is determined. You can extend [HttpGetResponse](https://github.com/Baseflow/flutter_cache_manager/blob/develop/lib/src/web/file_service.dart#L61) and override the [get fileExtension](https://github.com/Baseflow/flutter_cache_manager/blob/develop/lib/src/web/file_service.dart#L115).

**Comment by spiderion** [comment]
@thank you.
