### ISSUE TITLE
When is cache emptied

### ISSUE THREAD

**Issue by febg11** [Baseflow/flutter_cache_manager#174]
## 💬 Questions and Help

Hi
I was wondering If I use this setup 
```
super(key,
      maxAgeCacheObject: Duration(days: 1),
      maxNrOfCacheObjects: 75);
```
In my subclass, do the files that have a cache longer that 1 day automatically get deleted by your library?

If so could please explain when it happens and under what scenarios.

Thanks for the great library

**Comment by febg11** [comment]
Could anybody please help me with my questions?

**Comment by renefloor** [comment]
I explained it here: https://github.com/Baseflow/flutter_cache_manager/issues/106#issuecomment-613267998

In your settings it deletes files that haven't been used for a day.

**Comment by febg11** [comment]
Ok. I see that in <a href="">this</a> issue, you also talk about setting a custom FileService to set the validTill cache header. Is this necessary or will your library set this by default based on the maxAgeCacheObject: Duration(days: 1) I provide to the constructor.

My scenario is caching firebase storage files for short/long periods. I currently have 2 custom classes that extend BaseCacheManager.

I haven't really done caching before so sorry if I am completely off.

**Comment by renefloor** [comment]
There are 2 periods for the cache:
1) validity: how long is the object valid? That is determined by the http headers and if you want to change this you need to override the fileservice. 
2) age for cleanup: even though a file might be valid for a year you might still want to remove it from the cache after a week or so, that is determined by the maxAgeCacheObject in the constructor.

If I understand correctly you want to set the period for case 2 right?

**Comment by febg11** [comment]
Yes  I want some files to be stored for 3 weeks and other files to be stored for only 1 day. Does this mean I only need to set the age for cleanup?

What does the validity actually do of the maxAgeCacheObject determines how long it will be stored.

**Comment by renefloor** [comment]
The maxAgeCacheObject looks at the last time the file is used, so if you set it on a week but use the file every day it will never be removed. However, when the file is outdated it asks the server if there is a newer version. It can send the newer version or say it is still up to date (status code 304)

**Comment by febg11** [comment]
Ok what is the default value for the file becoming outdated? Is there a way to get it to never ask the server for a newer version once it's loaded successfully once.

**Comment by renefloor** [comment]
Than you have to make sure the cache header indicates the file is valid for a very long time or override the fileservice

**Comment by febg11** [comment]
Hi

I have updated my cache manager to use a file service. Could you tell me If I have done it correctly.


```
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'package:http/http.dart' as http;

class LongCacheManager extends BaseCacheManager {
  static const key = "longCustomCacheKey";

  static LongCacheManager _instance;

  factory LongCacheManager() {
    if (_instance == null) {
      _instance = new LongCacheManager._();
    }
    return _instance;
  }

  LongCacheManager._() : super(key,
      maxAgeCacheObject: Duration(days: 30),
      maxNrOfCacheObjects: 150);

  Future<String> getFilePath() async {
    var directory = await getTemporaryDirectory();
    return p.join(directory.path, key);
  }

}


class LongCacheHttpFileService implements FileService {
  http.Client _httpClient;
  LongCacheHttpFileService({http.Client httpClient}) {
    _httpClient = httpClient ?? http.Client();
  }

  @override
  Future<FileServiceResponse> get(String url, {Map<String, String> headers = const {}}) async {

    final req = http.Request('GET', Uri.parse(url));
    req.headers.addAll(headers);

    final httpResponse = await _httpClient.send(req);
    httpResponse.headers.addAll({'cache-control': 'max-age=${Duration(days: 182).inSeconds}'});

    return HttpGetResponse(httpResponse);
  }
}
```

I want to allow files to be valid for 182 days (to prevent them from being re-downloaded from the server too often) and delete them if the file is not fetched from cache for a consecutive 30 days.

Does this code do this?

**Comment by renefloor** [comment]
Looks good to me, although I would override the HttpGetResponse like this: (didn't test the code)
```
class LongGetResponse extends HttpGetResponse {
  LongGetResponse(HttpResponse _response) : super(_response);

  @override
  DateTime get validTill {
    // Without a cache-control header we keep the file for a week
    var ageDuration = const Duration(days: 182);
    return _receivedTime.add(ageDuration);
  }
}
```

**Comment by febg11** [comment]
Doesn't that do the same as what I have done by adding cache control to the response.headers in the fileservice get method I overrode?

E.g.
```
final httpResponse = await _httpClient.send(req);
httpResponse.headers.addAll({'cache-control': 'max-age=${Duration(days: 182).inSeconds}'});

return HttpGetResponse(httpResponse)
```


I tried setting the req but it did nothing so I set the response headers.

**Comment by renefloor** [comment]
Yes, that why I said 'looks good to me'. Setting the request headers doesn't change the cache-control indeed, because normally a client cannot say anything about these headers. The server has to set them.

**Comment by febg11** [comment]
I changed the Constructor to use StreamedResponse which seems to work e.g.

```
  LongGetResponse(http.StreamedResponse _response) : super(_response);
```

But i cannot seem to access _receivedTime as it is a private variable. Does this answer mean I cannot access it from my sub class?
https://stackoverflow.com/a/58715883/11284664

**Comment by renefloor** [comment]
Didn't this work for you?
```
final httpResponse = await _httpClient.send(req);
httpResponse.headers.addAll({'cache-control': 'max-age=${Duration(days: 182).inSeconds}'});

return HttpGetResponse(httpResponse)
```

**Comment by febg11** [comment]
It did I just thought it would be neater to use the sub class.

**Comment by renefloor** [comment]
ah ok, _receivedTime is just the DateTime.now() of the creation of the HttpGetResponse object. For your case it is not about seconds, so you can also just do this:
```
  @override
  DateTime get validTill {
    var ageDuration = const Duration(days: 182);
    return DateTime.now().add(ageDuration);
  }
```

**Comment by febg11** [comment]
Ok thank you for all the help :) 

Sorry for being a nuisance but I have one last question.
```
File file = await ShortCacheManager().getSingleFile(webURL);
// .... a bunch of code
file.delete()
```
If I call file.delete() on a file that has been received from your library does this actually delete the file from the cache or does it keep it in cache as the file is a copy of what is it cache?

**Comment by renefloor** [comment]
The file is the file in the cache. Of course it doesn't delete it from the server.

**Comment by febg11** [comment]
No i mean does it clear the file in the cache or does it just delete a copy file of the cache (i.e it will still be in cache and I can get it again without redownloading)

**Comment by renefloor** [comment]
I don't know what you mean with a copy file of the cache, so I just said that the file you delete is the file in the cache so it is deleted from the cache and you need to redownload it. I've no idea what other file you could delete here.

**Comment by febg11** [comment]
Dont worry Rene i think I may have confused you. You have answered all my questions. Thank you for all the help and the library :)
