### ISSUE TITLE
DownloadProgress totalSize is always null

### ISSUE THREAD

**Issue by Aoi-hosizora** [Baseflow/flutter_cache_manager#188]
### Configuration

**Version:** 1.1.3

**Platform:** Android

### Description

I use `DefaultCacheManager` in my customer ImageProvider (for [PhotoViewGallery](https://github.com/renancaraujo/photo_view)), and I want to use progress to show download progress. But the DownloadProgress.totalSize from FileResponse Stream is always null.

Here is my code: (Some code is copied from `CachedNetworkImageProvider` `_image_provider_io.dart`)

```dart
@override
ImageStreamCompleter load(image_provider.LocalOrNetworkImageProvider key, DecoderCallback decode) {
  final chunkEvents = StreamController<ImageChunkEvent>();
  return MultiFrameImageStreamCompleter(
    codec: _loadAsync(key, chunkEvents, decode).first,
    chunkEvents: chunkEvents.stream,
    scale: 1.0, // key.scale
    informationCollector: () sync* {
      yield DiagnosticsProperty<ImageProvider>(
        'Image provider: $this \n Image key: $key',
        this,
        style: DiagnosticsTreeStyle.errorProperty,
      );
    },
  );
}

Stream<ui.Codec> _loadAsync(
  LocalOrNetworkImageProvider key,
  StreamController<ImageChunkEvent> chunkEvents,
  DecoderCallback decode,
) async* {
  assert(key == this);

  var file = await this.file();
  if (await file.exists()) {
    var bytes = await file.readAsBytes();
    var decoded = await decode(bytes);
    yield decoded;
    onFile?.call();
    return;
  }
  try {
    var mngr = DefaultCacheManager();
    await for (var result in mngr.getFileStream(
      key.url,
      withProgress: true,
      headers: headers,
    )) {
      if (result is DownloadProgress) {
        print('${result.downloaded} ${result.totalSize}'); // <<<
        chunkEvents.add(ImageChunkEvent(
          cumulativeBytesLoaded: result.downloaded,
          expectedTotalBytes: result.totalSize, // <<<
        ));
      }
      if (result is FileInfo) {
        var file = result.file;
        var bytes = await file.readAsBytes();
        var decoded = await decode(bytes);
        yield decoded;
      }
    }
  } catch (e) {
    rethrow;
  } finally {
    onNetwork?.call();
    await chunkEvents.close();
  }
}
```

```dart
PhotoViewGallery.builder(
  loadingBuilder: (context, ImageChunkEvent event) => Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: [
      // xxx
      CircularProgressIndicator( // <<<
        value: event == null || event.expectedTotalBytes == null ? null
        : (event.cumulativeBytesLoaded ?? 0.0) / event.expectedTotalBytes,
      ),
    ],
  ),
  // xxx
  builder: (BuildContext context, int index) => PhotoViewGalleryPageOptions(
  // xxx
    imageProvider: LocalOrNetworkImageProvider( // <<<
      url: widget.images[index],
      file: () async => _presenter.getFile(index: index),
    ),
  ),
),
```

### Screenshot

![image](https://user-images.githubusercontent.com/31433480/84365319-dd8b6180-ac03-11ea-894c-21e327ce6d9a.png)

**Comment by renefloor** [comment]
Can you give me a url you try to download? Than I can try to reproduce it

**Comment by Aoi-hosizora** [comment]
@renefloor Here are some test images: 
http://momoniji.com/wordpress/wp-content/uploads/2020/06/yuri-couple200611021.jpg
http://momoniji.com/wordpress/wp-content/uploads/2020/06/yuri-couple200611035.jpg
http://momoniji.com/wordpress/wp-content/uploads/2020/06/yuri-couple200611039.jpg

I use HEAD request and I can get the success size, but result.totalSize is null.

![image](https://user-images.githubusercontent.com/31433480/84407225-23185080-ac3d-11ea-88b8-bca2f506901e.png)

**Comment by Aoi-hosizora** [comment]
@renefloor I just work out an ugly solution:

```dart
int totalSize;
http.head(key.url, headers: {
  'User-Agent': 'curl/7.55.1',
  'Accept': '*/*',
  'Accept-Encoding': '',
}).then((data) {
  totalSize = int.tryParse(data.headers['content-length']);
});
await for (var result in stream) {
  if (result is DownloadProgress) {
    print('${result.downloaded} ${result.totalSize ?? totalSize}');
    chunkEvents.add(ImageChunkEvent(
      cumulativeBytesLoaded: result.downloaded,
      expectedTotalBytes: result.totalSize ?? totalSize,
    ));
  } else if (result is FileInfo) {
    var file = result.file;
    var bytes = await file.readAsBytes();
    var decoded = await decode(bytes);
    yield decoded;
  }
}
```

I just see that curl has no `Accept-Encoding` header, and postman will fill it automatically.

(curl: default header -> ignore `Accept-Encoding`)
![image](https://user-images.githubusercontent.com/31433480/84413939-e3a13280-ac43-11ea-9b00-41cd016ffef9.png)

(postman: default header -> `Accept-Encoding: gzip, deflate, br`)
![image](https://user-images.githubusercontent.com/31433480/84414110-15b29480-ac44-11ea-8155-12d946ba01ae.png)

(postman: ignore `Accept-Encoding`)
![image](https://user-images.githubusercontent.com/31433480/84414081-0d5a5980-ac44-11ea-9211-0eeab7a51e29.png)

I wonder that even I don't set `Accept-Encoding` header when using http package and Dio package. but `Content-Length` is still not exist.

(package:http/http.dart: set `Accept-Encoding` empty)
![image](https://user-images.githubusercontent.com/31433480/84414763-92de0980-ac44-11ea-8528-2720fbe60bfb.png)

(package:http/http.dart: ignore `Accept-Encoding`)
![image](https://user-images.githubusercontent.com/31433480/84414936-a1c4bc00-ac44-11ea-92c1-328b1b87b5fb.png)

**Comment by renefloor** [comment]
@Aoi-hosizora just for me to check if I understand you correctly. Adding `'Accept-Encoding': '',` in the header fixes it for you?

So that means 
```
    mngr.getFileStream(
      url,
      withProgress: true,
      headers: {
        'Accept-Encoding': '',
      },
    );
```
Should already be enough?

**Comment by Aoi-hosizora** [comment]
@renefloor Oh, I have forgotten the `header` parameter. Yeah, I set `Accept-Encoding` empty in `headers` and it works. It may not be necessary to use `http` package. Thx.

```go
var mngr = DefaultCacheManager();
var h = headers ?? {};
h['Accept-Encoding'] = '';
var stream = mngr.getFileStream(key.url, withProgress: true, headers: h);
int totalSize;
http.head(key.url, headers: {
  'User-Agent': 'curl/7.55.1',
  'Accept': '*/*',
  'Accept-Encoding': '',
}).then((data) {
  totalSize = int.tryParse(data.headers['content-length']);
});
await for (var result in stream) {
  if (result is DownloadProgress) {
    print('${result.downloaded} ${result.totalSize} $totalSize'); // <<<
    chunkEvents.add(ImageChunkEvent(
      cumulativeBytesLoaded: result.downloaded,
      expectedTotalBytes: result.totalSize ?? totalSize,
    ));
  } else if (result is FileInfo) {
    var file = result.file;
    var bytes = await file.readAsBytes();
    var decoded = await decode(bytes);
    yield decoded;
  }
}
```

![image](https://user-images.githubusercontent.com/31433480/85295272-414e3e00-b4d2-11ea-825d-683e99391fcf.png)
