### ISSUE TITLE
Is there any way to store and retrieve already downloaded json into cache? 

### ISSUE THREAD

**Issue by DhavalRKansara** [Baseflow/flutter_cache_manager#196]
## 💬 Questions and Help

Using this library is there any way using which I can store the JSON response in the cache which I have got in the API call. and the same way retrieves it too?

**Comment by renefloor** [comment]
Did you just try it? It just saves the body of the response to a file, so if the content is a json string it should just store the json string to a file. You can read the file with `String contents = await file.readAsString();`

**Comment by DhavalRKansara** [comment]
Actually I checked there are some methods available which will do the https request and saves the response in the cache and return as well as but my use case is something different...

What I want is I am using Dio for the API call I'll receive a response for the **ABC** API call and I'll do some modification in the response JSON and then I want to store that Json or Model into the cache.

Is there any way to perform the above scenario using this library?

**Comment by renefloor** [comment]
You could use the method `putFile`, but you'd have to change it to bytes. You also shouldn't just use getFile, because that will update you json if it is outdated and you'll lose the modifications.
