### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by fmatosqg** [Baseflow/flutter_cache_manager#197]
## 🚀 Feature Requests

Be able to run this lib in linux :) 

### Describe the feature

Currently when using flutter_cached_network_image on linux there's a crash, since `sqflite` doesn't support linux: 

https://github.com/tekartik/sqflite/issues/470

### Platforms affected (mark all that apply)
- [x] :penguin: linux
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
In PR #193 I'm making it easier to use different ways of caching on different platforms. If that is completed I guess it shouldn't be hard to use an alternative for sqflite.

**Comment by alextekartik** [comment]
I created a document here https://github.com/tekartik/sqflite/blob/develop/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md that shows how to make it work on Linux and Windows. I just tested successfully on Linux.

**Comment by fmatosqg** [comment]
@renefloor keen to see how that works out. If for some reason you decide that it's not a good path for linux support pls ping me and I'd love to hear you out and help with a new plan.

**Comment by hpoul** [comment]
@renefloor are you still working on #193 ? btw. what would you think about generally getting rid of the sqflite dependency? afaik it is only used to store an index of the cached files. and by default those are just 200 entries? I guess it wouldn't even be too inefficient to keep that in memory and just periodically serialize to a json file? 😅️ especially compared to message channel overhead.

or looking at some dart-only stores like https://pub.dev/packages/hive (never used it, but looks promising)

**Comment by renefloor** [comment]
@hpoul, @escamoteur and @moovida what do you think of the solution in PR #226?

**Comment by hpoul** [comment]
@renefloor 👍️ from the first glance of it, I'm a fan.. one fewer extension 🎉️ just 10 seconds ago, i've hit a bug in my app due to cache manager and some weird sqlite error .. I'll  be the first to switch ;-)

<img width="733" alt="Screen Shot 2020-09-23 at 15 33 53" src="https://user-images.githubusercontent.com/313066/94019609-44e3b080-fdb2-11ea-9504-b70b01bef67e.png">

(I guess this happens on macos when it is open *forever* maybe even with a few hibernation/standby cycles 😅️ but this won't happen with json files :-) )

**Comment by moovida** [comment]
@renefloor I like the idea a lot.

**Comment by renefloor** [comment]
@hpoul that's a weird error indeed. Maybe the database is already open when he tries to open it?

**Comment by hpoul** [comment]
@renefloor i don't think so.. but i doubt it has anything to do with the cache manager :-) maybe not even sqlite .. i've also had occasional strange DNS resolve (or network) issues pop up, when the flutter app runs over multiple days.. but it's not really reproducible, once restarted it works again for days.. maybe there is still something weird going on in the mac flutter embedder, or the dart runtime.. 🤷️
