### ISSUE TITLE
add option to change databases path to NSLibraryDirectory on ios

### ISSUE THREAD

**Issue by The-Redhat** [Baseflow/flutter_cache_manager#202]
## 🏗 Enhancement Proposal

Currently the cache database file is stored in the documents directory on iOS. When one uses [UIFileSharingEnabled ](https://medium.com/@sasude9/download-files-in-files-app-in-ios-11-b676b89cf6be) for example to make downloaded files available in the Files app, the cache database file also shows up in that directory. According to [Apple](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) one shouldn't store none-user files in the DocumentDirectory. Instead the NSLibraryDirectory is recommended. Moreover the flutter `path_provider` package suggest to use `getLibraryDirectory` for database files. 
![photo5228850717417123257](https://user-images.githubusercontent.com/33162310/87773795-f3ec9480-c823-11ea-8edf-e24d52f37bf2.jpg)
### Pitch

I suggest to give users the option to specify where they want to store the database file.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by cbenhagen** [comment]
I think putting it in `NSApplicationSupportDirectory` by default would be a much better fit. It lies within the `NSLibraryDirectory`.

Related issue:
https://github.com/Baseflow/flutter_cache_manager/issues/205
