### ISSUE TITLE
db File always visible via iTunes FileSharing (getApplicationDocumentsDirectory)

### ISSUE THREAD

**Issue by filly82** [Baseflow/flutter_cache_manager#205]
I have been experimenting with the FileSharing Feature of iOS where it is possible to share Files between my App via Itunes.
I noticed that a lot of my own caches (this package' sqflite db, another sqflite db file and a few directories) were visible in iTunes and I don't want that. 
I have managed to make all of those cache files invisible to Itunes except the db File of this package, by ensuring that all those files get saved into `getApplicationSupportDirectory()` instead of `getApplicationDocumentsDirectory()`. It is the recommended way when I don't want to expose my files to the user

This is my own FileCacheManager implementation where I also replaced getApplicationDocumentsDirectory with getApplicationSupportDirectory, but the db File (FAppFileCache.db) is still visible through iTunes

What am i doing wrong?

```
class MyFileCacheManager extends BaseCacheManager {
  static const key = "FAppFileCache";

  static MyFileCacheManager _instance;

  factory MyFileCacheManager() {
    if (_instance == null) {
      _instance = new MyFileCacheManager._();
    }
    return _instance;
  }

  MyFileCacheManager._() : super(key,
      maxAgeCacheObject: Duration(days: 7),
      maxNrOfCacheObjects: 1536);

  Future<String> getFilePath() async {
    var directory = await pathProvider.getApplicationSupportDirectory();
    return path.join(directory.path, key);
  }
}
```
If I remember correctly there was a corresponding directory in which the files are stored. This directory is not visible **any more** in iTunes after my change. Why is the db File still visible?

**Comment by josh-burton** [comment]
I'm running into this issue as well. It's strange because the default cache manager uses the correct path (/Library/Caches) but the db file is still visible in the Files application.

**Comment by filly82** [comment]
> I'm running into this issue as well. It's strange because the default cache manager uses the correct path (/Library/Caches) but the db file is still visible in the Files application.

As you can see there is still no reply to my issue 😔

**Comment by renefloor** [comment]
Sorry I cannot always keep up with all the issues. 
The database file is stored separately from the other files. By default all files are stored in a cache folder, which means the OS can delete any of them at any time. You don't want to lose the database file because of that.

The path for the database is set in the CacheStore (although on the develop branch it is moved a bit, so can be somewhere else now): https://github.com/Baseflow/flutter_cache_manager/blob/master/flutter_cache_manager/lib/src/cache_store.dart#L45

By default it uses [getDatabasePath](https://pub.dev/documentation/sqflite/latest/sqflite/getDatabasesPath.html) for that, which is the Documents directory on iOS.

**Comment by josh-burton** [comment]
Ah, that makes sense. I think it would be best to change this to getApplicationSupportDirectory() instead and migrate from the previous path.

Or maybe make it configurable instead?

**Comment by renefloor** [comment]
Yes indeed, that is the same that is also used for the newer [JsonCacheInfoRepository](https://github.com/Baseflow/flutter_cache_manager/blob/develop/flutter_cache_manager/lib/src/storage/cache_info_repositories/json_cache_info_repository.dart)
