### ISSUE TITLE
 [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: NoSuchMethodError: The getter 'modalBarrierDismissLabel' was called on null.

### ISSUE THREAD

**Issue by siddheshJungade** [Baseflow/flutter_cache_manager#210]
## 💬 Questions and Help
I am new to flutter I am facing bug App is working properly but alert box is not showing 

ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: NoSuchMethodError: The getter 'modalBarrierDismissLabel' was called on null.
E/flutter ( 9979): Receiver: null
E/flutter ( 9979): Tried calling: modalBarrierDismissLabel
E/flutter ( 9979): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 9979): #1      Alert.show (package:rflutter_alert/src/alert.dart:54:55)
E/flutter ( 9979): #2      _QuizzlerState.checkAnswer.<anonymous closure> (package:quizzler/main.dart:49:11)
E/flutter ( 9979): #3      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
E/flutter ( 9979): #4      _QuizzlerState.checkAnswer (package:quizzler/main.dart:20:5)
E/flutter ( 9979): #5      _QuizzlerState.build.<anonymous closure> (package:quizzler/main.dart:116:23)
E/flutter ( 9979): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:19)
E/flutter ( 9979): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter ( 9979): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 9979): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:528:11)
E/flutter ( 9979): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 9979): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 9979): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 9979): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 9979): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 9979): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 9979): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 9979): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 9979): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:219:19)
E/flutter ( 9979): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 9979): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:157:7)
E/flutter ( 9979): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:103:7)
E/flutter ( 9979): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:87:7)
E/flutter ( 9979): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 9979): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 9979): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 9979): #26     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 9979): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 9979):

**Comment by siddheshJungade** [comment]
this is code 

void checkAnswer(bool userPickedAns){
    setState(() {
      if(quizBrain.isFinish() == true){
        print('allert');
        Alert(
          context: context,
          type: AlertType.warning,
          title: "RFLUTTER ALERT",
          desc: "Flutter is more awesome with RFlutter Alert.",
          buttons: [
            DialogButton(
              child: Text(
                "FLAT",
                style: TextStyle(color: Colors.white, fontSize: 20),
              ),
              onPressed: () => Navigator.pop(context),
              color: Color.fromRGBO(0, 179, 134, 1.0),
            ),
            DialogButton(
              child: Text(
                "GRADIENT",
                style: TextStyle(color: Colors.white, fontSize: 20),
              ),
              onPressed: () => Navigator.pop(context),
              gradient: LinearGradient(colors: [
                Color.fromRGBO(116, 116, 191, 1.0),
                Color.fromRGBO(52, 138, 199, 1.0)
              ]),
            )
          ],
        ).show();

        quizBrain.reset();

        scoreKeeper = [];
      }
      else{
        if(quizBrain.getQuestionAns() == userPickedAns){
          scoreKeeper.add(
              Icon(
                Icons.check,
                color: Colors.green,
              )
          );
        }
        else{
          scoreKeeper.add(
              Icon(
                Icons.close,
                color: Colors.red,
              )
          );
        }
        quizBrain.nextQuestion();
      }

    });
  }

**Comment by renefloor** [comment]
Sorry for the late response, but this has nothing to do with flutter_cache_manager. For generic Flutter questions it is better to use StackOverflow.

But I also don't understand how `Alert.show()` would work within setState. You can have a look at the AlertDialog example to show dialogs: https://api.flutter.dev/flutter/material/AlertDialog-class.html
