### ISSUE TITLE
Expose CacheInfoRepository, CacheStore, CacheOject

### ISSUE THREAD

**Issue by hpoul** [Baseflow/flutter_cache_manager#212]
## 🏗 Enhancement Proposal

It looks like those three objects are not exposed using the default `package:flutter_cache_manager/flutter_cache_manager.dart`. But especially `CacheStore` seems to be meant to be interacted directly by user of the library.

I would propose to include the exports in `flutter_cache_manager.dart` for:

* src/cache_store.dart
* src/storage/cache_info_repository.dart
* src/storage/cache_object.dart

**Comment by timekone** [comment]
Yes, please!
