### ISSUE TITLE
Can getSingleFile() ever return null?

### ISSUE THREAD

**Issue by febg11** [Baseflow/flutter_cache_manager#214]
I am using getSingleFile() in a FutureBuilder and I was wondering whether it can ever return null. I have noticed if you put junk data in the parameter it will throw an exception or timeout if the url provides no file. 

I don't want my fileSnapshot.hasData boolean to always be false if its null, so it would be good if this always throws an exception.

**Comment by danielroek** [comment]
Hi @febg11 ,

The hasData getter on a  ASyncSnapshot is used to check if the snapshot data is null or not. This class is part of the Flutter framework and works as intended. 
If an error is thrown by the flutter_cache_manager plugin you are able to catch it by using fileSnapshot.hasError and change your UI accordingly. 

For more information about FutureBuilder you might want to checkout [the Flutter Documentation.](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html)

Hope this helps.
