### ISSUE TITLE
No host specified in URI

### ISSUE THREAD

**Issue by yyzl0418** [Baseflow/flutter_cache_manager#215]
Invalid argument(s): No host specified in URI
1 #0 _HttpClient._openUrl (dart:_http/http_impl.dart:2313)
--
2 #1 _HttpClient.openUrl (dart:_http/http_impl.dart:2203)
3 #2 IOClient.send (package:http/src/io_client.dart:31)
4 #3 HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:32)
5 #4 WebHelper._download (package:flutter_cache_manager/src/web/web_helper.dart:76)
6 #5 WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:58)
7 <asynchronous suspension>
8 #6 WebHelper.downloadFile.<anonymous closure> (package:flutter_cache_manager/src/web/web_helper.dart:39)
9 <asynchronous suspension>
10 .(:0)

**Comment by renefloor** [comment]
That is an error when your url is invalid. Does the url start with `http(s)://`?

**Comment by yyzl0418** [comment]
I used "cached_network_image 2.3.1"  ,this error always appear

**Comment by yyzl0418** [comment]
> That is an error when your url is invalid. Does the url start with `http(s)://`?

I used "cached_network_image 2.3.1" ,this error always appear

**Comment by renefloor** [comment]
What's the url of the image you try to show?

**Comment by yyzl0418** [comment]
i don't know,but Why is the wrong address used cache

**Comment by yyzl0418** [comment]
> What's the url of the image you try to show?

i don't know,but Why is the wrong address used cache

**Comment by renefloor** [comment]
I don't know what you mean. The cache manager tries to download the file you request from the internet. Once it is downloaded it caches it and serves it to you. This error is clearly a fail during the download phase. `No host specified in URI` means that the url doesn't start with http or https, that's why I ask you the url, because the url is wrong.

**Comment by yyzl0418** [comment]
if url is wrong,I hope image use placeholder ,but it throw a exception

> I don't know what you mean. The cache manager tries to download the file you request from the internet. Once it is downloaded it caches it and serves it to you. This error is clearly a fail during the download phase. `No host specified in URI` means that the url doesn't start with http or https, that's why I ask you the url, because the url is wrong.

if url is wrong,I hope image use placeholder ,but it throw a exception

**Comment by renefloor** [comment]
It shouldn't throw an exception, but only log the exception. Does your app crash from this? If you use the errorWidgetBuilder I think the error isn't logged as well.

**Comment by yyzl0418** [comment]
> It shouldn't throw an exception, but only log the exception. Does your app crash from this? If you use the errorWidgetBuilder I think the error isn't logged as well.

my app caught this exception, and submit server

**Comment by renefloor** [comment]
I think it is just logging in that case. If you really find an app crashing due to this please reopen this issue, but I really think just the placeholder is shown. You can also try this yourself by trying to show a wrong image url on purpose.

**Comment by yyzl0418** [comment]
> I think it is just logging in that case. If you really find an app crashing due to this please reopen this issue, but I really think just the placeholder is shown. You can also try this yourself by trying to show a wrong image url on purpose.
the before "cached_network_image 2.3.1" is Ok,"2.3.1" this error is too many

**Comment by yyzl0418** [comment]
> I think it is just logging in that case. If you really find an app crashing due to this please reopen this issue, but I really think just the placeholder is shown. You can also try this yourself by trying to show a wrong image url on purpose.

the before "cached_network_image 2.3.1" is Ok,"2.3.1" this error is too many

**Comment by renefloor** [comment]
I think it should disappear if you supply an errorBuilder, you can use the same content of course as in the placeholder. Or maybe you can tweak how your app logs these exceptions

**Comment by yyzl0418** [comment]
![企业微信截图_e7a0fb17-fdf1-4ce4-890e-5dbc09ea352e](https://user-images.githubusercontent.com/14289945/91705471-96cc5880-ebaf-11ea-9aaa-2b26b26bf011.png)

this method throw a exception ,but you don't catch
@renefloor

**Comment by renefloor** [comment]
That's right. It is the imageprovider that handles the exception. Same happens in NetworkImage: https://github.com/flutter/flutter/blob/e8c942104bb4b414b67e303a54b00e8fc45c67a6/packages/flutter/lib/src/painting/_network_image_io.dart

**Comment by yyzl0418** [comment]
> That's right. It is the imageprovider that handles the exception. Same happens in NetworkImage: https://github.com/flutter/flutter/blob/e8c942104bb4b414b67e303a54b00e8fc45c67a6/packages/flutter/lib/src/painting/_network_image_io.dart

why need rethrow,my app caught this error

**Comment by renefloor** [comment]
What do you mean? Which rethrow?

**Comment by yyzl0418** [comment]
> What do you mean? Which rethrow?

![企业微信截图_4a5fe699-c372-41a3-8779-31a5393ed8f6](https://user-images.githubusercontent.com/14289945/91714036-7acfb380-ebbd-11ea-8c43-a92719c04857.png)
this "rethrow"

**Comment by renefloor** [comment]
Yes, but that's NetworkImage, that source from the main Flutter repo. I used that as an example to show that an ImageProvider needs to throw an exception when loading fails to the ImageWidget can handle the failed loading.

I showed this code that the Flutter ImageWidget logs the error silently if you don't provide an errorListener:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/image.dart#L127-L143

```        FlutterError.reportError(FlutterErrorDetails(
          context: ErrorDescription('image failed to precache'),
          library: 'image resource service',
          exception: exception,
          stack: stackTrace,
          silent: true,
        ));```
