### ISSUE TITLE
Custom Cache Key Does Not Exist (The named parameter 'key' isn't defined)

### ISSUE THREAD

**Issue by zenkog** [Baseflow/flutter_cache_manager#221]
It seems that the Custom Key as specified [here](https://github.com/Baseflow/flutter_cache_manager#custom-cache-key) does not work in the code.

```
await getSingleFile(url);
```
This does not have `key` parameters in it. It says: 

```
The named parameter 'key' isn't defined.  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'key'.
```

I'm using `flutter_cache_manager: ^1.4.2`
and here is my Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.200, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by renefloor** [comment]
Thats right, it is because it is not released yet. 
The master branch is always the released version: https://github.com/Baseflow/flutter_cache_manager/tree/master

I'll try to release it soon, but it is kind of a breaking change, so I'll combine it with some other larger changes and that still needs some testing.

**Comment by zenkog** [comment]
Thanks for the information. It would be helpful to add some of these information in the documentation (in github repository)

**Comment by zenkog** [comment]
> Thats right, it is because it is not released yet.
> The master branch is always the released version: https://github.com/Baseflow/flutter_cache_manager/tree/master
> 
> I'll try to release it soon, but it is kind of a breaking change, so I'll combine it with some other larger changes and that still needs some testing.

Which version is a dev version? How do I get it? Thanks

**Comment by renefloor** [comment]
> Which version is a dev version? How do I get it? Thanks

What do you mean? The current code on the development branch of github is not released yet. You can always use git sources in your pubspec, but I would really not recommend doing that as there is a reason it is not released yet.

> the documentation (in github repository)

The documentation in pub is leading if you get the package from there. I don't really see why I should add documentation in github that the github code in the development branch might not be released yet.
