### ISSUE TITLE
Does the expiry date count from the first time the file is saved or from the last time it was accessed?

### ISSUE THREAD

**Issue by zenkog** [Baseflow/flutter_cache_manager#223]
Sorry if it was documented somewhere. Somehow I couldn't find it.

For instance, `ProfileImageCache` inherits from `BaseCacheManager`:

```
class ProfileImageCache extends BaseCacheManager {
  static const key = 'profileCache';

  static ProfileImageCache _instance;

  factory ProfileImageCache() {
    _instance ??= ProfileImageCache._();
    return _instance;
  }

  ProfileImageCache._()
      : super(key,
            maxAgeCacheObject: Duration(days: 15),
            maxNrOfCacheObjects: 500,
            fileService: HttpFileService());

}
```

As you can see in the example above that the `maxAgeCacheObject` is set to 15 days. 

The question is, does the `maxAgeCacheObject` count down (if you could call it this way) always get reset whenever `getSingleFile` method gets called or does it not?

If yes, that means the file will be removed 15 days after the last access to that file. If no, that means the file will be removed 15 days after the first time downloaded in the device regardless if the user access it many times afterwards.

**Comment by renefloor** [comment]
There are 2 dates used by the package to see if the file is 'old'.

The maxAgeCacheObject and maxNrOfCacheObjects are used to clean the cache. The max age is relative to the last time you used the file. If the app hasn't used the image for a long time the file is removed from the cache. The maxNrOfCacheObjects are also sorted on when you last used the file.

When you do an API call the HTTP headers should also indicate for how long the cache is valid with the Cache-Control headers. When the file is too old according to these headers the cache tries to redownload the file. However, using the eTag header it can also get a response that the file is not changed and it gets a new validity date.

So the maxAgeCacheObject is used for the last access to the file, the HTTP headers are used for the last time the file is downloaded.

There is also an issue (#139) to improve the documentation on this.
