### ISSUE TITLE
Add Windows support or allow to pass in an initialized sqlite instance

### ISSUE THREAD

**Issue by escamoteur** [Baseflow/flutter_cache_manager#224]
Hi,

currently flutter_cache_manager doesn't work on Windows Desktop. therefore also cached_network_image doesn't work which I really need.

Implementing a Windows version would be one but probably the more difficult option. As it's possible to use sqlite on Windows following https://moor.simonbinder.eu/docs/other-engines/vm/

Would it be possible to add a static function tha allows is to pass an existing sqlite instance? This way we could use it not only on Windows, but also on Linux and probably mac.

**Comment by renefloor** [comment]
In PR #193 (which is close to finished) I made it easier to support different 'cache object providers' and the next thing I plan to do is write one that is not depending on sqlite. That will be the default on windows and linux

**Comment by escamoteur** [comment]
awesome!!!

**Comment by renefloor** [comment]
For windows I could enable 'in memory' caching, but that is pretty heavy on memory usage. I think it needs at least this PR to be finished: https://github.com/flutter/plugins/pull/2818

**Comment by escamoteur** [comment]
It works with the current version in the repo

  path_provider: 1.5.1
  path_provider_fde:
    git: 
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
