### ISSUE TITLE
stop download file

### ISSUE THREAD

**Issue by hatemragab** [Baseflow/flutter_cache_manager#227]
how to  stop downloading file

**Comment by renefloor** [comment]
Not possible at the moment

**Comment by hatemragab** [comment]
ok is there any way to make downloading stop? because it downloads in the background I can't stop it if the screen dispose called

**Comment by renefloor** [comment]
This is the place where the http stream is received and store on disk: https://github.com/Baseflow/flutter_cache_manager/blob/develop/flutter_cache_manager/lib/src/web/web_helper.dart#L166

We would implement a way to cancel this and delete the file that is already being saved.

I think we should add a method which checks if a url is being downloaded and add the url to some variable which is checked after each byte.

**Comment by hatemragab** [comment]
just if file downloading kindly add a method to stop downloading the file stream thanks

**Comment by renefloor** [comment]
Btw, I'm closing it as a duplicate of #208
