### ISSUE TITLE
Flutter Cache Manager BETA with Cached Network Image - FOR WINDOWS

### ISSUE THREAD

**Issue by andrebadini** [Baseflow/flutter_cache_manager#233]
## 💬 Questions and Help

When I try to use the beta dependency for Windows, I get the following error:

//-----------------------------------------------
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/cached_image_widget.dart(34,5): error G7D2AEF3C: Type 'BaseCacheManager' not found. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/cached_image_widget.dart(45,9): error G7D2AEF3C: Type 'BaseCacheManager' not found. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/image_provider/cached_network_image_provider.dart(39,5): error G7D2AEF3C: Type 'BaseCacheManager' not found. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/image_provider/cached_network_image_provider.dart(47,3): error G7D2AEF3C: Type 'BaseCacheManager' not found. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/image_provider/_image_provider_io.dart(29,9): error G7D2AEF3C: Type 'BaseCacheManager' not found. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/cached_image_widget.dart(34,5): error GBDFDE2CF: 'BaseCacheManager' isn't a type. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/cached_image_widget.dart(45,9): error GBDFDE2CF: 'BaseCacheManager' isn't a type. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/image_provider/cached_network_image_provider.dart(39,5): error GBDFDE2CF: 'BaseCacheManager' isn't a type. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Sources/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.3.2+1/lib/src/image_provider/_image_provider_io.dart(29,9): error GBDFDE2CF: 'BaseCacheManager' isn't a type. [C:\Users\andre\DevProjects\Flutter-BuySell(v1.1)\Mobile Source\flutter_buysell\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
//-----------------------------------------------

//-----------------------------------------------
**This is my PUBSPEC.YAML:**

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.3.2+1
  flutter_cache_manager: ^1.4.2

dependency_overrides:
  flutter_cache_manager: ^2.0.0-beta
//-----------------------------------------------

//-----------------------------------------------
**Flutter Doctor:**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [versÃ£o 10.0.19041.508], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!
//-----------------------------------------------

**Comment by renefloor** [comment]
Hmm sorry, I don't know why I thought that worked. (I did test, but maybe the pub upgrade failed without me noticing.) Will make a beta of cachednetworkimage soon.

**Comment by renefloor** [comment]
I just published 2.0.0-beta.1 with increased compatibility.

**Comment by andrebadini** [comment]
Thank you! It worked!
