### ISSUE TITLE
Get cache size

### ISSUE THREAD

**Issue by alr2413** [Baseflow/flutter_cache_manager#239]
Hi,
in the previous version 1.x.x, we can use the `await DefaultCacheManager().getFilePath()` syntax to get the default cache directory path. how should we get that path in the new version 2 since there is no "getFilePath()" method anymore?
Thanks in advance

**Comment by renefloor** [comment]
What's the usecase that you need to know the directory path?

**Comment by alr2413** [comment]
To calculate the cache size as mentioned in #83

**Comment by renefloor** [comment]
I've been thinking about adding the getFilePath again, but that is not really a great solution. For example for web there is not really a path, so it wouldn't be consistent over platforms. I think it is better to implement a method to get the cache size.

**Comment by alr2413** [comment]
Yea, i've checked the previous version of the package and figured out how to add the "getFilePath" method to my custom implementation. 
Thanks.

**Comment by kamike** [comment]
same question

**Comment by esiqveland** [comment]
Is there currently a way to get the total size of cache and the number of objects cached?

**Comment by aintend-com** [comment]
Is this implemented?

**Comment by jithware** [comment]
@renefloor how about something like: 

https://github.com/jithware/flutter_cache_manager/blob/develop/flutter_cache_manager/lib/src/cache_store.dart#L194-L198

**Comment by Nico04** [comment]
Related to https://github.com/Baseflow/flutter_cache_manager/issues/398
