### ISSUE TITLE
fileInfo.validTill returns creation date

### ISSUE THREAD

**Issue by mu10** [Baseflow/flutter_cache_manager#244]
## 🐛 Bug Report
It seems `fileInfo.validTill` always returns creation date. Yet `getFileFromCache` returns true instead of null despite stale period has passed. 

### Expected behavior
`fileInfo.validTill` returns creation date + stale period.
`getFileFromCache` returns null if valid till has passed.

### Reproduction steps
```
class RequestFromCache {
  static Future<FileInfo> getFileInfo(String uri, String databaseName,
      String fileName, Duration stalePeriod, int maxCached) async {
    CacheManager cacheManager = CacheManager(Config(databaseName,
        stalePeriod: stalePeriod, maxNrOfCacheObjects: maxCached));
    // Try from cache
    FileInfo fileInfo = await cacheManager.getFileFromCache(fileName);
    // If not on cache, download it. Download will also save it on cache.
    if (fileInfo == null)
      fileInfo = await cacheManager.downloadFile(uri, key: fileName);
    return fileInfo;
  }
}

const String _cacheDatabaseName = 'geocoding';
const Duration _cachePeriod = Duration(minutes: 5);
const int _cachedMax = 50;

Future<Map<String, dynamic>> _request(
      String requestUri, String cacheFilename) async {
    // Request cache
    FileInfo fileInfo = await RequestFromCache.getFileInfo(requestUri,
        _cacheDatabaseName, cacheFilename, _cachePeriod, _cachedMax);
    if (fileInfo != null) {
      debugPrint('>>> cache valid till:' + fileInfo.validTill.toString());
      FileSource source = fileInfo.source;
      if (source == FileSource.Cache)
        debugPrint('>>> source from cache');
      else if (source == FileSource.Online)
        debugPrint('>>> source from server');
      File file = fileInfo.file;
      if (file != null) {
        String json = await file.readAsString();
        return jsonDecode(json);
      }
    }
    return null;
  }
```

### Configuration
I'm using it to call Google Maps Geocoding API.
Tested on Android Emulator.

**Version:** 2.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
See my answer here: https://github.com/Baseflow/flutter_cache_manager/issues/249#issuecomment-729508473

Probably the geocoding API itself indicates that the result isn't valid for long, which sounds quite reasonable to me. 
The validity is not coming from the stale period that you set but from the API result.

**Comment by mu10** [comment]
Yeah I thought so. That mean it's not designed to be able to override the header if we set it manually? This kinda feel not like what we expect cache to do if we set it manually. And I think this behaviour is not written on package explanation/documentation.

**Comment by renefloor** [comment]
I agree that the documentation can be better and I'm working on that. However, you can override the behaviour if you want to. I created a gist to show how: https://gist.github.com/renefloor/0337275a8246c69a09775776de7de112

**Comment by mu10** [comment]
Going to try it later
