### ISSUE TITLE
File path is not the same as on Simulator

### ISSUE THREAD

**Issue by mikeRozen** [Baseflow/flutter_cache_manager#246]
## 🐛 Bug Report

Hi,
I am downloading a Facebook profile image which works fine after that I would like to have the File (I would like to upload it to the Firebase Storage) using the same url from facebook
```
DefaultCacheManager().getSingleFile(url);
```
Inspecting the LocalFile I get I see somethimh strange:
the path that I get is:
_/Users/myuse/Library/Developer/CoreSimulator/Devices/A5E8898B-4C35-4F89-BD91-A4FE771BF0D7/data/Containers/Data/Application/3D6B1A50-8A0A-4E92-94D1-21A7BECF02EC/Library/Caches/libCachedImageData/15c8ecf0-26a9-11eb-bbcb-d7f065956b72.jpg_
But when I try to open the path there is no such image i.e the path exists but the image name is different:
<img width="1234" alt="Screen Shot 2020-11-14 at 21 15 44" src="https://user-images.githubusercontent.com/11506268/99155285-279ad680-26bf-11eb-8f71-a413178af510.png">
As you can see the image name is differ so as a result I cant upload the image.
I deleted and reinstalled the app but still the same, I am not sure what I am doing wrong.
Fetching the image form the gallery works

### Expected behavior
Image name should be consistent 

### Reproduction steps
download image and get its File via url 

### Configuration

**Version:** 1.x

**Platform:** 
- [v] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
When the file is being redownloaded the file path changes. Maybe you did download the file a second time?
