### ISSUE TITLE
 Vibration when switching between listview elements

### ISSUE THREAD

**Issue by miksmtr** [Baseflow/flutter_cache_manager#251]
Hello, we development like instagram app.

have a problem like this as follow

[https://gfycat.com/chubbyfoolishdaddylonglegs](url)

and, fixed when using cache_network_image 
I would like to inform you

**Comment by renefloor** [comment]
You fixed it by using cache_network_image, or was cache_network_image the reason for the vibration. 
Can you create a small reproducable example so we might be able to fix this?
