### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by ryanheise** [Baseflow/flutter_cache_manager#253]
## 🚀 Feature Requests

See https://dart.dev/null-safety/migration-guide

### Contextualize the feature

This is necessary for packages that depend on flutter_cache_manager to use null safety (e.g. https://github.com/Baseflow/flutter_cached_network_image/issues/503)

At the time of writing, the `sqflite` dependency now has a null_safety prerelease, but `http` does not. Maybe `dart:io` can be used instead of `http`.

### Describe the feature

https://dart.dev/null-safety
https://dart.dev/null-safety/faq

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment]
Replacing http with dart:io would make the library incompatible with web. That would mean we need to create an separate httpclient for web and io, but that will almost like remaking http library. IMO it is better to wait for http to migrate.
The issue to watch: https://github.com/dart-lang/http/issues/501

**Comment by SarcasticNoodle** [comment]
http recently got the nullsafety version published: https://pub.dev/packages/http/versions/0.13.0-nullsafety.0

**Comment by pablo-johnson** [comment]
Hello, any update on this?

**Comment by renefloor** [comment]
I had some busy weeks and I didn't see any PR coming around, but I think I will have time to make the migration somewhere in the coming 2 weeks.
