### ISSUE TITLE
upgrade to rxdart ^0.25.0

### ISSUE THREAD

**Issue by aker99** [Baseflow/flutter_cache_manager#257]
upgrade to *rxdart* ^0.25.0

**Pitch**
I am using package in my projects with depends on `*0.25.0*, I can no longer upgrade packages which depend on flutter_cache_manager because of incompatibility issue with rxdart >= 0.25.0

**Comment by renefloor** [comment]
https://pub.dev/packages/flutter_cache_manager/changelog#210---2020-12-21
