### ISSUE TITLE
The "getSingleFile" and "getFileStream" methods cannot get the latest file after I update the file on the server.

### ISSUE THREAD

**Issue by dev-zhang** [Baseflow/flutter_cache_manager#260]
## 🐛 Bug Report

When I used the iOS simulator to test, after the image has been loaded and cached locally, I updated the image resource on the server, but did not change the file name of the image, so I got the same url.
When I called the "getSingleFile" method and passed this url, I did not get the updated image resource. I also tested the "getFileStream" method and got the same result.

### Expected behavior

After the pictures on the server are modified, expect to get the latest picture resources on the server.

### Configuration

**Version:** 1.x

I used version 1.4.2 and 2.1.0 respectively, both of which have the same problem.

**Comment by renefloor** [comment]
The question is how the app nows that the image changed on the server. The whole point of caching is that you don't download the image every time you need it. 

The library uses the HTTP cache-control headers which is standard web behavior:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

So you have two ways of controlling how the library behaves:
>Cache-Control: max-age=<seconds>

With the max-age you determine how often the library checks for new files. For example setting this to 60 will ensure that at most 1 minute after you change your image on the server the library will check for the new image. Not setting this header will default to 7 days.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
>The ETag HTTP response header is an identifier for a specific version of a resource. 

Setting the ETag helps keeping the data usage low. Often checking for new images isn't really a problem if you correctly implement the ETag. The ETag says like the current image is 'image 1'. The library will say to your server, 'hey do you have an image, I currently have image 1' and your server can respond with 'that's still the newest (304 NOT MODIFIED)' or 'hey it changed, here is a new one (200 with image)'.

**Comment by dev-zhang** [comment]
@renefloor Thank you very much for your reply.
The image on the server still uses the same file name after being modified, so the same URL is used when accessing the image.
But after testing with Postman or Chrome, I can confirm that the etag value before and after the modification is different.

I think the problem is that the `cacheFile.validTill.isBefore(DateTime.now())` judgment in the "getSingleFile" method will not trigger the download behavior, and will not find that the image resource needs to be updated (status code: 200, 202 ).

![image](https://user-images.githubusercontent.com/16589421/102879113-42adf280-4484-11eb-9985-f54a79fe68c1.png)

**Comment by renefloor** [comment]
Yes, that validTill value is coming from the `Cache-Control: max-age=` header. Some files are known to never change, so than it doesn't make sense to check every time you need the image. When this header value is not set the default is 7 days.

**Comment by dev-zhang** [comment]
@renefloor 
Thank you for your answers. I have learned.
