### ISSUE TITLE
Can not find the cached files on device

### ISSUE THREAD

**Issue by AminKaviani10** [Baseflow/flutter_cache_manager#266]
I am using this code to cache files on my app:

`var audioFile = await DefaultCacheManager().getSingleFile('fileUrl');`

When I ran the app, the files are being cached. But I can not find the path where the files are cached on the device.

This is the address which I get on debug mode:
"/data/user/0/{my_package_name}/cache/libCachedImageData/3a65ece0-5366-11eb-91e0-0f0ba53cd292.mp4"

But there is no such path on my device.

**Comment by ericel** [comment]
What exactly are you trying to do with the path. The library provides an option to use a key. That key should be what you use to identify the cache.
`var file = await instance.getSingleFile(url, key: key, headers: headers);`

**Comment by DonAlex1897** [comment]
> What exactly are you trying to do with the path. The library provides an option to use a key. That key should be what you use to identify the cache.
> `var file = await instance.getSingleFile(url, key: key, headers: headers);`

I want to physically access the file to see if the user can access it from the file manager.

**Comment by DonAlex1897** [comment]
Here is the answer to my question:

[https://stackoverflow.com/a/65815034/9953815](url)
