### ISSUE TITLE
Could not build example project in Xcode

### ISSUE THREAD

**Issue by cuong0993** [Baseflow/flutter_cache_manager#279]
## 🐛 Bug Report

I opened example project, open iOS workspace but cannot build it in Xcode.
Error is

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FMDatabaseQueue", referenced from:
      objc-class-ref in SqflitePlugin.o
ld: symbol(s) not found for architecture x86_64

<img width="1440" alt="Screen Shot 2021-02-12 at 17 44 32" src="https://user-images.githubusercontent.com/8237154/107758925-24fd5b00-6d5a-11eb-9cd7-f8538d66ada6.png">

### Expected behavior
Project can be built
### Reproduction steps
- Opened example project
- Open iOS workspace
- Build it in Xcode
### Configuration
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-arm, locale en-VN)
    • Flutter version 1.22.6 at /Users/cuong/Desktop/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cuong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

**Version:** 2.1.1

**Platform:** 
- [ x] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
I switched to stable, went to the example and did `flutter clean` and `flutter run`. This runs just fine on iOS. After that I could just 'open iOS module' from android studio and run it from xcode. Maybe `flutter clean` can help you?
