### ISSUE TITLE
update dependecy to image 3.0.0-nullsafety.0

### ISSUE THREAD

**Issue by robertoltrocha** [Baseflow/flutter_cache_manager#281]
Hi,
Could you update this dependency?

Thanks

`flutter_cache_manager >=2.1.0 depends on image ^2.1.18 and XXX depends on image 3.0.0-nullsafety.0, flutter_cache_manager >=2.1.0 is forbidden.`

**Comment by renefloor** [comment]
Should be fixed in `flutter_cache_manager: ^3.0.0`
