### ISSUE TITLE
Custom Cache Manager not working after version 2.0.0

### ISSUE THREAD

**Issue by pankajrohilla893** [Baseflow/flutter_cache_manager#282]
## 🐛 Bug Report

class CustomCacheManager {
  static const key = 'customCacheObject';
  static CacheManager instance = CacheManager(Config(key, stalePeriod: Duration(days: 120), maxNrOfCacheObjects: 1000));
}

Trying to make Custom Cache Manager like above but unable to do that, caching is not happening.

DefaultCacheManager() is working properly.

Accessing above like below:

var file = await CustomCacheManager.instance.downloadFile(
                    "${env.baseUrl}",
                    authHeaders: requestHeaders);

**Version:** 2.1.1

**Platform:** 
- [x] :iphone: iOS -version 14.4
- [ ] :robot: Android

**Comment by renefloor** [comment]
the `downloadFile` method always downloads the file (and puts it in the cache).
I tried your cacheManager with `getFileStream` and caching works as expected.
```
    CustomCacheManager.instance
        .getFileStream('https://via.placeholder.com/150', withProgress: false)
```
