### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by Ricky294** [Baseflow/flutter_cache_manager#287]
Can you please update dependencies?

> Running "flutter pub get" in {myprojectname}          
> Because flutter_cache_manager >=1.2.0 <3.0.0-nullsafety.0 depends on uuid ^2.0.2 and {myprojectname} depends on uuid ^3.0.1, flutter_cache_manager >=1.2.0 <3.0.0-nullsafety.0 is forbidden.

**Comment by cto-leaps** [comment]
+1 please 🙏

**Comment by peterbyCom** [comment]
Yeah, Pls fix the problem. lol

**Comment by renefloor** [comment]
Should be fixed in `flutter_cache_manager: ^3.0.0`
