### ISSUE TITLE
Operand of null-aware operation

### ISSUE THREAD

**Issue by PcolBP** [Baseflow/flutter_cache_manager#298]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/67896443/111296637-fcb09700-864c-11eb-9f25-169777645be8.png)

### Expected behavior
Just this error in console right after debug or realease install

### Reproduction steps

**Version:** 3.0.0-nullsafety.1

**Platform:** 
Android API 29
Haven't tested yet IOS Platform

**Flutter Doctor**
![image](https://user-images.githubusercontent.com/67896443/111296847-3da8ab80-864d-11eb-9566-6fca7b9ee4ad.png)

**Comment by itmediacreations** [comment]
Solution: after upgrading sqflite, now getDatabasesPath returns non-nullable String
