### ISSUE TITLE
Cancel a started download

### ISSUE THREAD

**Issue by marcodecarolisidt** [Baseflow/flutter_cache_manager#309]
## 🚀 Feature Requests

When we start a very big download with 
```
DefaultCacheManager().downloadFile(url)
``` 
I would like to give the possibility to the user to cancel the download

### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by renefloor** [comment]
Thanks for the feature request. It is a duplicate of #208
Please at a 👍 to the original post in that issue.
