### ISSUE TITLE
Cancel function on Download stream file 

### ISSUE THREAD

**Issue by vernalclareai** [Baseflow/flutter_cache_manager#311]
## 🏗 Enhancement Proposal

DefaultCacheManager().getFileStream(downloadUrl, withProgress: true);

I wanted to cancel the download, but there is no option.
Any idea on it?

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
It is not possible yet indeed. Please give a thumbs up to this older existing issue: #208
