### ISSUE TITLE
percentage progress download

### ISSUE THREAD

**Issue by EmanueleVolpato** [Baseflow/flutter_cache_manager#330]
it would be handy to have the download percentage when I download a file

**Comment by Faaatman** [comment]
You view the progress using the following:
```Dart
getFileStream(url, withProgress: true)
```
Use that stream in a stream builder. if loading is true use snapshot.data as Download progress to get the progress.
```Dart
var loading = !snapshot.hasData || snapshot.data is DownloadProgress;
```

**Comment by EmanueleVolpato** [comment]
how to use getfilestream in a stram builder?

**Comment by Jassirlink** [comment]
is there any example for showing the download progress of file

**Comment by EmanueleVolpato** [comment]
Future<void> downloadPdf(int index, String url) async {
    await for (var result in DefaultCacheManager().getFileStream(
      url,
      key: index.toString(),
      withProgress: true,
    )) {
      if (result is DownloadProgress) {
        //print('${result.downloaded} ${result.totalSize}');
        var totalSizePdf;
        totalSizePdf = result.totalSize;
        if (result.totalSize == null) {
          totalSizePdf = 10000000;
        }
        setState(() {
          progress[index] =
              (result.downloaded / 0.00000001) / (totalSizePdf / 0.00000001);
          percentualeDownload[index] = (result.downloaded / 0.00000001) /
              (totalSizePdf / 0.00000001) *
              100;
        });
      }
    }
  }
}

**Comment by EmanueleVolpato** [comment]
> is there any example for showing the download progress of file , when i use the above one , it shows the instance of download progress , not getting the exact value

 Future<void> downloadPdf(int index, String url) async {
    await for (var result in DefaultCacheManager().getFileStream(
      url,
      key: index.toString(),
      withProgress: true,
    )) {
      if (result is DownloadProgress) {
        //print('${result.downloaded} ${result.totalSize}');
        var totalSizePdf;
        totalSizePdf = result.totalSize;
        if (result.totalSize == null) {
          totalSizePdf = 10000000;
        }
        setState(() {
          progress[index] =
              (result.downloaded / 0.00000001) / (totalSizePdf / 0.00000001);
          percentualeDownload[index] = (result.downloaded / 0.00000001) /
              (totalSizePdf / 0.00000001) *
              100;
        });
      }
    }
  }
}
