### ISSUE TITLE
Application directory changes Directory name automatically on re-launch

### ISSUE THREAD

**Issue by zeddyyz** [Baseflow/flutter_cache_manager#336]
## 💬 Questions and Help

I'm using this to download files from firebase storage, which works perfectly. Code I use for downloading is as follows:

"""
var fileInfo = await DefaultCacheManager().getSingleFile(url);

if (fileInfo != null) {
await DefaultCacheManager().downloadFile(url);

fileInfo = await DefaultCacheManager()
    .getSingleFile(url);

print("Episode downloaded: " +
    fileInfo.uri.path);
}
"""

With fileInfo.uri.path I save it to device local storage using Hive. Then the path is provided to a just_audio player widget which retrieves the file from the file path and plays the audio.

This process works perfectly when I download and play the audio in one go but then when I relaunch the app, the directory name changes. For ex: first it was "D2153E40-EF0A-4130-B717-D76A1B243394" and then relaunch app and it changed to "96767D5D-D425-4804-BBCF-1493BA1D5D31".

I've tried to utilize key with custom name and stalePeriod, but have had no luck.

Can I please get guidance on how to persist the application directly name where the file is stored?

**Comment by renefloor** [comment]
Yes that's how iOS works. The application directory isn't fixed and can always change, see also this answer: https://developer.apple.com/forums/thread/92693

If you want to save the path you should store the relative path and get the absolute path with path_provider using `getTemporaryDirectory()`. Or use your key with `cachemanager.getFileFromCache(String key, {bool ignoreMemCache = false});` and get the path from the returned file.
