### ISSUE TITLE
[Feature request] Add retry mechanism

### ISSUE THREAD

**Issue by JulianAssmann** [Baseflow/flutter_cache_manager#340]
## 🚀 Feature Requests

A retry mechanism for when the initial download of a file over the network fails. This could be analogous to the fetch strategy implementation in the [flutter_image](https://pub.dev/packages/flutter_image) package, supporting exponential backoff, timeouts and so on.

### Contextualize the feature

This should be a feature of the `CacheManager.getFileStream(...)` method. An optional `fetchStrategy` parameter could be added, allowing to specify the timeouts, retry count and exponential backoff for the initial download.

### Describe the feature

[flutter_image](https://pub.dev/packages/flutter_image) already provides a good implementation of this feature.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by huakucha** [comment]
when the retry mechanism can be used?
