### ISSUE TITLE
should export the file_system

### ISSUE THREAD

**Issue by yk3372** [Baseflow/flutter_cache_manager#365]
```dart
export 'src/storage/file_system/file_system.dart';
export 'src/storage/file_system/file_system_io.dart';
export 'src/storage/file_system/file_system_web.dart';
```

The IOFileSystem can't import for below code.

```
CacheManager(
    Config(
      key,
      stalePeriod: const Duration(days: 7),
      maxNrOfCacheObjects: 20,
      repo: JsonCacheInfoRepository(databaseName: key),
      fileSystem: IOFileSystem(key),
      fileService: HttpFileService(),
    ),
  )
```

**Comment by yk3372** [comment]
@petermichaux  please fix it, thanks

**Comment by yk3372** [comment]
same to https://github.com/Baseflow/flutter_cached_network_image/issues/710

**Comment by Technorocker** [comment]
@montyr75 Hello, I tried adding that import but didnt work for me. Has anyone figured this out yet? I'm trying to use this instead of cached video player plugin but cant figure out what to import to get the IOFileSystem referenced properly.

**Comment by shen601020** [comment]
> @montyr75您好，我尝试添加该导入，但对我不起作用。有人已经弄清楚了吗？我正在尝试使用它而不是缓存视频播放器插件，但无法弄清楚要导入什么才能正确引用 IOFileSystem。

试试：import 'package:flutter_cache_manager/src/storage/file_system/file_system_io.dart';
