### ISSUE TITLE
flutter_cache_manager at least give a proper example  

### ISSUE THREAD

**Issue by Kalyanb447-github** [Baseflow/flutter_cache_manager#369]
got an error 
var file = await FirebaseCacheManager().downloadFile(url);

firebase_storage/unknown] location should not be a full URL.
i have already given the full address 
String url =
          'https://firebasestorage.googleapis.com/v0/b/feel-the-kiss.appspot.com/o/audios%2F10.wav?alt=media&token=ea66d553-e46d-45e7-90e7-29477d4305b1';
i am unable to understand please help !

**Comment by rivella50** [comment]
Have you tried without the URL scheme?
