### ISSUE TITLE
How to get the total memory usage of the app memory

### ISSUE THREAD

**Issue by nicolasvahidzein** [Baseflow/flutter_cache_manager#398]
I was expecting to get a function to see the total size of the app cached before knowing if it was a good moment to clear the cache. I don't see that function anywhere.

Thanks for the help.

**Comment by seanhamstra** [comment]
Looking for this too!

**Comment by romatallinn** [comment]
Yep, me too.

**Comment by Nico04** [comment]
That would be handy I agree

**Comment by martijn00** [comment]
https://github.com/Baseflow/flutter_cache_manager/pull/449
