### ISSUE TITLE
recommended to upgrade path_provider for flutter_cache_manager_firebase

### ISSUE THREAD

**Issue by haizadvnet** [Baseflow/flutter_cache_manager#404]
This issue already solved for `flutter_cache_manager` as mentioned here https://github.com/Baseflow/flutter_cache_manager/issues/294, but not on `flutter_cache_manager_firebase`.

Do you consider to update it on `flutter_cache_manager_firebase` as well?

I got error log below:
```
And because apps depends on firebase_core ^2.4.1, every version of flutter_cache_manager_firebase requires path_provider ^1.4.0.
So, because apps depends on both path_provider ^2.0.2 and flutter_cache_manager_firebase any, version solving failed.
```

**Comment by d9media** [comment]
Looks like this packages is abandoned? I was looking for a version compatible with the newer versions of firebase_core_platform_interface required by cloud_firestore ^4.12.0.
