### ISSUE TITLE
Check if KEY is already cached

### ISSUE THREAD

**Issue by elana-voss** [Baseflow/flutter_cache_manager#409]
## 🚀 Feature Requests

I would like to read all the currently cached keys. 

Or to be able to check if a certain key is already cached.

### Contextualize the feature

More complex usage of the CacheManager requires knowledge of the currently cached keys.

### Describe the feature

**Example**

My app shows thumbnails. Clicking a thumbnail displays the associated, large image.

The app indicates whether the large image is already downloaded and cached or not.

For this indication, the app needs to query the Cache Manager if the associated key of the large image is already cached or not.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by martijn00** [comment]
https://github.com/Baseflow/flutter_cache_manager/pull/354
