### ISSUE TITLE
 Upgrade http dependency to 1.x 

### ISSUE THREAD

**Issue by gustav3d** [Baseflow/flutter_cache_manager#413]
Upgrade to http plugin to 1.0 and hence migration to Dart 3.0

**Comment by ersha80** [comment]
you could do it yourself, find the yaml file at /Users/***/.pub-cache/hosted/pub.flutter-io.cn/flutter_cache_manager-3.3.0, just change http: ^0.13.0 to http: ^1.0.0.

**Comment by abhinovpankaj** [comment]
Any plans upgrading to latest http package?

**Comment by Carapacik** [comment]
Updated https://pub.dev/packages/flutter_cache_manager/versions/3.3.1

**Comment by mvanbeusekom** [comment]
Closing this issue as the dependency has been updated per version 3.3.1
