### ISSUE TITLE
Please consider upgrade the dependencies to the latest Dart 3 / File 7.0

### ISSUE THREAD

**Issue by MagnusJohansson** [Baseflow/flutter_cache_manager#417]
## 🏗 Enhancement Proposal

Since the [package file](https://pub.dev/packages/file/changelog) is now at v7.0.0 , to be Dart3 compliant, it would nice if flutter_cache_manager also upgrades its dependencies to include file version 7.0.0

```
Resolving dependencies...
Because no versions of cached_network_image match >3.2.3 <4.0.0 and cached_network_image 3.2.3 depends on flutter_cache_manager ^3.3.0, cached_network_image ^3.2.3 requires flutter_cache_manager ^3.3.0.
Because flutter_cache_manager 3.3.0 depends on file ^6.0.0 and no versions of flutter_cache_manager match >3.3.0 <4.0.0, flutter_cache_manager ^3.3.0 requires file ^6.0.0.
Thus, cached_network_image ^3.2.3 requires file ^6.0.0.
So, because my_app depends on both cached_network_image ^3.2.3 and file ^7.0.0, version solving failed.
```

### Pitch

Pitch? Well, if this package is intended to be relevant in the near future , it would behove the maintainers to keep up to date.

### Platforms affected (mark all that apply)
- [ x] :iphone: iOS
- [ x] :robot: Android

**Comment by MagnusJohansson** [comment]
... I see there's already a PR for #414

**Comment by clintonrocksmith** [comment]
Yes this is important for us @renefloor 

Is there anything we can do to get the release rolled out?

Thanks mate

**Comment by clintonrocksmith** [comment]
FYI, I emailed them using their company form on their website

**Comment by WongResearch** [comment]
I second what @clintonrocksmith said - this is important. Would be great if this can be looked at. Thank you in advance @renefloor

**Comment by hadoudait** [comment]
any updates on this?

**Comment by Carapacik** [comment]
Updated https://pub.dev/packages/flutter_cache_manager/versions/3.3.1

**Comment by mateusfccp** [comment]
Although the changelog says that the new version supports `file: 7.0.0`, having both `file: ^7.0.0` and `flutter_cache_manager: ^3.3.1` in my `pubspec.yaml` results in the following:

```sh
host@HOST ~/D/r/c/tory (flutter_v3.10)> flutter pub get
Resolving dependencies... (7.0s)
Because path_provider >=2.0.0 <2.0.8 depends on
  path_provider_linux ^2.0.0 and flutter_cache_manager
  >=3.0.0-nullsafety.0 depends on path_provider ^2.0.0,
  flutter_cache_manager >=3.0.0-nullsafety.0 requires
  path_provider_linux ^2.0.0 or path_provider ^2.0.8.
And because path_provider >=2.0.8 depends on path_provider_linux
  ^2.0.1, flutter_cache_manager >=3.0.0-nullsafety.0 requires
  path_provider_linux ^2.0.0.
And because path_provider_linux >=2.0.0 <2.1.8 depends on
  xdg_directories ^0.2.0 and path_provider_linux >=2.1.8 depends on
  xdg_directories >=0.2.0 <2.0.0, flutter_cache_manager
  >=3.0.0-nullsafety.0 requires xdg_directories >=0.2.0 <2.0.0.
And because xdg_directories >=0.2.0 depends on process ^4.0.0
  which depends on file ^6.0.0, flutter_cache_manager
  >=3.0.0-nullsafety.0 requires file ^6.0.0.
So, because media_content depends on both file ^7.0.0 and
  flutter_cache_manager ^3.3.1, version solving failed.
```

I had to revert to `file: ^6.0.0` for this package to work.

**Comment by Carapacik** [comment]
I think this error with xdg_directories

**Comment by sparrow001** [comment]
I agree, I am also having a version solve conflict between a package and path_provider, which boils down to the process package using `file: ^6.0.0`.

**Comment by Carapacik** [comment]
process removed from xdg_directories 
https://pub.dev/packages/xdg_directories/changelog#101

Still waiting for the PR megre to work correctly with file 7.0.0
https://github.com/Baseflow/flutter_cached_network_image/pull/845
