### ISSUE TITLE
error http ^0.13.0 

### ISSUE THREAD

**Issue by ghazalcomputer** [Baseflow/flutter_cache_manager#422]
please help me
when i get pub get show this error

Because flutter_cache_manager 3.3.0 depends on http ^0.13.0 and no versions of flutter_cache_manager match

3.3.0 <4.0.0, flutter_cache_manager ^3.3.0 requires http ^0.13.0.
And because flutter_map >=5.0.0 depends on http ^1.0.0, flutter_map >=5.0.0 is incompatible with
flutter_cache_manager ^3.3.0.
And because cached_network_image 3.2.3 depends on flutter_cache_manager ^3.3.0 and no versions of
cached_network_image match >3.2.3 <4.0.0, flutter_map >=5.0.0 is incompatible with cached_network_image ^3.2.3.
So, because metrohamkar depends on both cached_network_image ^3.2.3 and flutter_map ^5.0.0, version solving
failed.

**Comment by salba360496** [comment]
Use this in pubspec.yaml file
dependency_overrides:
  http: ^1.1.0

**Comment by Carapacik** [comment]
Updated https://pub.dev/packages/flutter_cache_manager/versions/3.3.1
