### ISSUE TITLE
How can I get the total size of the cache or get the cache path?

### ISSUE THREAD

**Issue by CPRen0** [Baseflow/flutter_cache_manager#441]
I'd like to show the cache size for users, please how can I get the total size of the cache or get the cache path?

**Comment by boyXiong** [comment]
+1  are you solve that ?

**Comment by CPRen0** [comment]
> +1 are you solve that ?

After reading the source code, you can know the cache path.
'getTemporaryDirectory()'

`class IOFileSystem implements FileSystem {
  final Future<Directory> _fileDir;
  final String _cacheKey;

  IOFileSystem(this._cacheKey) : _fileDir = createDirectory(_cacheKey);

  static Future<Directory> createDirectory(String key) async {
    final baseDir = await getTemporaryDirectory();
    final path = p.join(baseDir.path, key);

    const fs = LocalFileSystem();
    final directory = fs.directory(path);
    await directory.create(recursive: true);
    return directory;
  }

  @override
  Future<File> createFile(String name) async {
    final directory = await _fileDir;
    if (!(await directory.exists())) {
      await createDirectory(_cacheKey);
    }
    return directory.childFile(name);
  }
}`

**Comment by boyXiong** [comment]
I want to customize the cache path to manage these cached files without having them delete themselves. Are you implementing the FileSystem yourself? Thank you

**Comment by CPRen0** [comment]
> I want to customize the cache path to manage these cached files without having them delete themselves. Are you implementing the FileSystem yourself? Thank you

I'm sorry, I didn't do that

**Comment by CPRen0** [comment]
> I want to customize the cache path to manage these cached files without having them delete themselves. Are you implementing the FileSystem yourself? Thank you

我只是使用了默认的存储方式，在默认的基础上进行了一个简单的封装，把过期时间和最大存储数量进行了个配置

**Comment by boyXiong** [comment]
牛逼啊， 是自己实现了 FileSystem 中的 createFile 方法吗，这个方法 可以用来实现自定义存储路径吗，谢谢

**Comment by CPRen0** [comment]
> 牛逼啊， 是自己实现了 FileSystem 中的 createFile 方法吗，这个方法 可以用来实现自定义存储路径吗，谢谢

没有没有，我只是在DefaultCacheManager上进行修改的，存储方式仍和原来一样

**Comment by boyXiong** [comment]
这样啊，谢谢

**Comment by martijn00** [comment]
https://github.com/Baseflow/flutter_cache_manager/pull/449
