### ISSUE TITLE
Cannot upgrade rxdart to latest

### ISSUE THREAD

**Issue by mulderpf** [Baseflow/flutter_cache_manager#458]
### Old (and correct) behavior
I was able to use the latest version of rxdart together with flutter_cache_manager

### Current behavior
When I update rxdart to the latest package, I get the following issue:
`Resolving dependencies...
Because flutter_cache_manager 3.3.2 depends on rxdart ^0.27.7 and no versions of flutter_cache_manager match >3.3.2 <4.0.0, flutter_cache_manager ^3.3.2 requires rxdart ^0.27.7.
So, because LondonBusPal depends on both flutter_cache_manager ^3.3.2 and rxdart ^0.28.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on rxdart: flutter pub add rxdart:^0.27.7
exit code 1`

### Reproduction steps
Update rxdart to version 0.28.0

**Comment by renefloor** [comment]
Fixed in flutter_cache_manager: ^3.3.3
