### ISSUE TITLE
Platform is not supported after migrating to WASM 

### ISSUE THREAD

**Issue by LoadJulz** [Baseflow/flutter_cache_manager#465]
## 🐛 Bug Report

After I have build my flutter web with WASM the app failed because of `flutter_cache_manager`. The log says: `Unsupported operation: Platform is not supported` when executing for instance  `final response = await DefaultCacheManager().getSingleFile(requestUrl);` Is the package already ready for WASM? 

**Version:** 3.4.0

**Comment by martijn00** [comment]
https://github.com/Baseflow/flutter_cache_manager/commit/c41a9bd38afc02582d0831e8d1bd8226b5692874
