### ISSUE TITLE
Download Progress as stream

### ISSUE THREAD

**Issue by ened** [Baseflow/flutter_cache_manager#70]
My current project features the download of somewhat large files (20~30mb) which require the display of such elements.

It would be great if I can retrieve the download progress in a Stream to drive progress bars or other user interface elements.

**Comment by badboy-tian** [comment]
+1

**Comment by furkankurt** [comment]
+1

**Comment by jimgreer** [comment]
+1

**Comment by saviourdog** [comment]
+2

**Comment by FCMHUB** [comment]
+1

**Comment by wochen85** [comment]
+1

**Comment by gjrjf** [comment]
+1

**Comment by suragch** [comment]
This issue was opened over a year ago. Still no response? That's unfortunate because it means I may have to abandon flutter_cache_manager.

**Comment by renefloor** [comment]
I'm working on improving the library. I guess this PR will make it easier to accomplish: https://github.com/Baseflow/flutter_cache_manager/pull/148. It makes the downloaded content available as a stream instead of a complete body. @suragch feel free to contribute.

**Comment by suragch** [comment]
@renefloor Actually, since making that comment I discovered `getFile()` which also returns a stream. So it seems that this is already available, correct?

**Comment by renefloor** [comment]
No, `getFile()` doens't return a file as a stream, but it returns a stream of files. 
When the file is in the cache, but outdated, it first returns the cached file and then tries to update the cached files. When successful it also returns the updated file. In that way it makes sure the file is quickly returned, but when outdated the users also gets the updated file.

**Comment by suragch** [comment]
@renefloor Thanks for that comment. That saved me a lot of time. I had misunderstood the usage of that method and was in the process of integrating it into my application.

**Comment by suragch** [comment]
I'm willing to consider contributing to #148 depending on the time frame and what needs to be done. How far away are you from something that would allow downloading content as a stream? What exactly would you like help on?

**Comment by renefloor** [comment]
Currently the whole proces of saving the file to storage happens in the webhelper. I think that should first be moved out of there, because webhelper should only manage the download and return the bytestream, and I think the cachemanager or the cachestore should handle the saving and then there we should implement the logic of proces. 
This commit at least makes the total size of the content available: https://github.com/Baseflow/flutter_cache_manager/pull/153/commits/a6ab372b746052d8e08b1c5c6746dc4f26e0b444

**Comment by suragch** [comment]
This issue appears to be solved by [version 1.2.0](https://pub.dev/packages/flutter_cache_manager#-changelog-tab-). That was a great update! Tested and working on Android and iOS. Thank you, @renefloor

**Comment by renefloor** [comment]
@suragch thanks for mentioning me. I'll close this issue now :)
