### ISSUE TITLE
Limit the number of concurrent fetches

### ISSUE THREAD

**Issue by alextekartik** [Baseflow/flutter_cache_manager#77]
Thanks for the plugin. I'm using it currently (through the cached_network_image plugin but I think my issue is more related to this package) to display a list of about 5000 lines where each line has a thumbnail url. 

As you might expect it generates a log of fetches and sqflite writes and it seems to sometimes lead to some 'stuttering'.

Sometimes I would like this cache manager to be less efficient (i.e less download). Maybe there could be a pool and the base cache manager could allow for a poolResourceCount so for example no more that 4 images are fetched in parallel.

Additionnaly. Sometimes I know I'm going to display a page of 50 images. Currently it leads to 50 writes where a sqlite batch would be more efficient (I know sqflite is fast compare to fetching images). I have not looked much at the API but is there a way to cache multiple files in one call (something like downloadFiles) that could in future improve its implementation to limit the number of concurrent fetches and group sqflite writes).

As a side note, when an image is missing (404), it generates a lot of warning in the output, I just wonder if we could 'hide' subsequent warning', i.e. display it only once.

Thanks!

**Comment by renefloor** [comment]
The warnings from the exception should be fixed now. The ideas for fetching multiple images at once or limiting the number of parallel fetches are interesting. Will look into that sometime.

**Comment by quetool** [comment]
> As a side note, when an image is missing (404), it generates a lot of warning in the output, I just wonder if we could 'hide' subsequent warning', i.e. display it only once.

I came here for the same thing. I develope on on a "staging" remote DB wich have a looooot of fake users each one with an image url but no image, so I get 404 exception for all those users and they are a lot! I can not read my console log until flutter_cache_manager ends logging the exception... Can I do something?

I comment the `throw e;` line right now but I prefer a better solution if there is...

```
Stream<FileInfo> getFile(String url, {Map<String, String> headers}) async* {
    var cacheFile = await getFileFromCache(url);
    if (cacheFile != null) {
      yield cacheFile;
    }
    if (cacheFile == null || cacheFile.validTill.isBefore(DateTime.now())) {
      try {
        var webFile = await webHelper.downloadFile(url, authHeaders: headers);
        if (webFile != null) {
          yield webFile;
        }
      } catch (e) {
        if (cacheFile == null) {
          // throw e;
        }
      }
    }
  }
```
